'use strict';
require('../backend/core/env').loadEnv();
const test=require('node:test');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const {Client}=require('pg');
const {randomUUID}=require('node:crypto');const {hashPassword}=require('../backend/core/auth');
const totp=require('../backend/core/totp');
const enabled=!!process.env.DATABASE_URL&&!!process.env.MIGRATION_DATABASE_URL&&!!process.env.MAT_BOOTSTRAP_OWNER_PASSWORD;
const httpTest=enabled?test:test.skip;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function startServer(port){const env={...process.env,PORT:String(port),NODE_ENV:'development',MAT_DB_MODE:'postgres',MAT_EPHEMERAL:'0'};delete env.NODE_TEST_CONTEXT;const child=spawn(process.execPath,['server.js'],{cwd:require('node:path').join(__dirname,'..'),env,stdio:['ignore','pipe','pipe'],windowsHide:true});let errors='';child.stderr.on('data',x=>{errors+=x});return{child,getErrors:()=>errors};}
async function waitReady(base,proc){for(let i=0;i<40;i++){if(proc.child.exitCode!==null)throw new Error(`Server berhenti saat boot: ${proc.getErrors()}`);try{const r=await fetch(`${base}/api/runtime`);if(r.ok)return;}catch{}await delay(100);}throw new Error(`Server tidak ready: ${proc.getErrors()}`);}
async function stop(proc){if(proc.child.exitCode!==null)return;proc.child.kill('SIGTERM');await Promise.race([new Promise(r=>proc.child.once('exit',r)),delay(3000)]);if(proc.child.exitCode===null)proc.child.kill('SIGKILL');}
httpTest('PostgreSQL HTTP E2E: transaksi dan sesi bertahan setelah restart server',async()=>{
  const port=45000+Math.floor(Math.random()*1000),base=`http://127.0.0.1:${port}`;let proc=startServer(port),cookie,csrf,doc,child,customer;
  try{
    await waitReady(base,proc);let response=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:process.env.MAT_BOOTSTRAP_OWNER_USERNAME,password:process.env.MAT_BOOTSTRAP_OWNER_PASSWORD})});assert.equal(response.status,200);cookie=response.headers.get('set-cookie').split(';')[0];let body=await response.json();csrf=body.csrfToken;
    const contracts=[
      ['/api/dashboard',x=>x.kpi&&x.health&&x.attention&&Array.isArray(x.activeJobs)],['/api/approvals',x=>Array.isArray(x.items)],['/api/notifications',x=>Array.isArray(x.items)],
      ['/api/customers',x=>Array.isArray(x.items)],['/api/suppliers',x=>Array.isArray(x.items)],['/api/products',x=>Array.isArray(x.items)],['/api/employees',x=>Array.isArray(x.items)],['/api/inventory',x=>Array.isArray(x.items)],
      ['/api/accounting/summary',x=>x.profitLoss&&Array.isArray(x.trialBalance)],['/api/tax/summary',x=>Array.isArray(x.deadlines)&&Array.isArray(x.documents)],['/api/audit',x=>Array.isArray(x.items)],['/api/jobs',x=>Array.isArray(x.items)],
      ['/api/system/users',x=>Array.isArray(x.items)],['/api/system/settings',x=>x.company?.bank&&Array.isArray(x.approvalMatrix)],['/api/system/monitoring',x=>x.api&&x.storage&&x.security&&x.jobs&&x.sse],['/api/system/self-test',x=>Array.isArray(x.results)&&typeof x.releaseBlocked==='boolean'],['/api/auth/devices',x=>Array.isArray(x.items)]
    ];
    for(const [endpoint,valid] of contracts){response=await fetch(`${base}${endpoint}`,{headers:{cookie}});assert.equal(response.status,200,endpoint);body=await response.json();assert.ok(valid(body),`Kontrak tidak cocok: ${endpoint}`);}
    response=await fetch(`${base}/api/documents`,{method:'POST',headers:{cookie,'content-type':'application/json','x-csrf-token':csrf,'idempotency-key':`http-e2e-${Date.now()}`},body:JSON.stringify({type:'QUOTATION',title:'HTTP persistence test',amount:125000,payload:{source:'automated-test'}})});assert.equal(response.status,201);doc=await response.json();assert.equal(doc.status,'DRAFT');
    response=await fetch(`${base}/api/documents/${doc.id}`,{method:'PATCH',headers:{cookie,'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({version:doc.version,title:'HTTP persistence updated'})});assert.equal(response.status,200);doc=await response.json();
    for(const action of ['submit','approve','start','complete','close']){response=await fetch(`${base}/api/documents/${doc.id}/action`,{method:'POST',headers:{cookie,'content-type':'application/json','x-csrf-token':csrf,'idempotency-key':`http-e2e-${action}-${Date.now()}`},body:JSON.stringify({action})});if(response.status!==200)throw new Error(`${action}: ${await response.text()}`);doc=await response.json();}
    assert.equal(doc.status,'CLOSED');
    response=await fetch(`${base}/api/documents/${doc.id}/convert`,{method:'POST',headers:{cookie,'content-type':'application/json','x-csrf-token':csrf,'idempotency-key':`http-convert-${Date.now()}`},body:'{}'});assert.equal(response.status,201);body=await response.json();child=body.child;assert.equal(child.documentType,'SALES_ORDER');
    response=await fetch(`${base}/api/documents/${doc.id}`,{headers:{cookie}});body=await response.json();assert.equal(response.status,200);assert.equal(body.relations.length,1);
    response=await fetch(`${base}/api/customers`,{method:'POST',headers:{cookie,'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({code:`HTTP-${Date.now()}`,name:'HTTP Master Test',city:'Bekasi'})});assert.equal(response.status,201);customer=await response.json();response=await fetch(`${base}/api/customers/${customer.id}`,{method:'PATCH',headers:{cookie,'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({city:'Jakarta'})});body=await response.json();assert.equal(response.status,200);assert.equal(body.city,'Jakarta');
    await stop(proc);proc=startServer(port);await waitReady(base,proc);
    response=await fetch(`${base}/api/auth/session`,{headers:{cookie}});assert.equal(response.status,200);body=await response.json();assert.ok(body.user);assert.ok(body.csrfToken);
    response=await fetch(`${base}/api/documents/${doc.id}`,{headers:{cookie}});assert.equal(response.status,200);body=await response.json();assert.equal(body.title,'HTTP persistence updated');assert.equal(body.status,'CLOSED');assert.equal(body.version,7);
  }finally{
    await stop(proc);if(doc){const admin=new Client({connectionString:process.env.MIGRATION_DATABASE_URL});await admin.connect();try{await admin.query(`DELETE FROM idempotency_records WHERE operation LIKE $1 OR response_body->>'id'=$2`,[`documents.convert:${doc.id}%`,doc.id]);if(child){await admin.query('DELETE FROM document_lines WHERE document_id=$1',[child.id]);await admin.query('DELETE FROM document_relations WHERE parent_document_id=$1 OR child_document_id=$1',[child.id]);await admin.query('DELETE FROM audit_logs WHERE entity_id=$1',[child.id]);await admin.query('DELETE FROM business_documents WHERE id=$1',[child.id]);}await admin.query('DELETE FROM document_lines WHERE document_id=$1',[doc.id]);await admin.query('DELETE FROM audit_logs WHERE entity_id=$1',[doc.id]);await admin.query('DELETE FROM business_documents WHERE id=$1',[doc.id]);await admin.query('DELETE FROM domain_event_outbox WHERE payload->>\'entityId\'=$1',[doc.documentNumber]);if(customer){await admin.query('DELETE FROM audit_logs WHERE entity_id=$1',[customer.id]);await admin.query('DELETE FROM customers WHERE id=$1',[customer.id]);}}finally{await admin.end();}}
  }
});
httpTest('PostgreSQL HTTP auth: kegagalan login di-commit untuk lockout',async()=>{
  const admin=new Client({connectionString:process.env.MIGRATION_DATABASE_URL});await admin.connect();const id=randomUUID(),username=`lockout_${Date.now()}`,password='Valid!Password-For-Test-9281';let proc;
  try{const branch=(await admin.query('SELECT id FROM branches ORDER BY created_at LIMIT 1')).rows[0];await admin.query(`INSERT INTO app_users(id,username,password_hash,display_name,branch_id,role,branch_scope,must_change_password) VALUES($1,$2,$3,'Lockout Test',$4,'employee',NULL,false)`,[id,username,hashPassword(password),branch.id]);const port=46000+Math.floor(Math.random()*1000),base=`http://127.0.0.1:${port}`;proc=startServer(port);await waitReady(base,proc);for(let i=0;i<2;i++){const r=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:'wrong-password'})});assert.equal(r.status,401);}const row=(await admin.query('SELECT failed_login_count FROM app_users WHERE id=$1',[id])).rows[0];assert.equal(row.failed_login_count,2);
  }finally{if(proc)await stop(proc);await admin.query('DELETE FROM login_history WHERE user_id=$1',[id]).catch(()=>{});await admin.query('DELETE FROM app_users WHERE id=$1',[id]).catch(()=>{});await admin.end();}
});
httpTest('PostgreSQL HTTP auth: ganti sandi wajib dan MFA TOTP lengkap',async()=>{
  const admin=new Client({connectionString:process.env.MIGRATION_DATABASE_URL});await admin.connect();const id=randomUUID(),username=`mfa_${Date.now()}`,temporary='Temporary!Password-9281',fresh='Fresh!Password-For-MFA-9281';let proc;
  try{const branch=(await admin.query('SELECT id FROM branches ORDER BY created_at LIMIT 1')).rows[0];await admin.query(`INSERT INTO app_users(id,username,password_hash,display_name,branch_id,role,branch_scope,must_change_password) VALUES($1,$2,$3,'MFA Test',$4,'employee',NULL,true)`,[id,username,hashPassword(temporary),branch.id]);const port=47000+Math.floor(Math.random()*1000),base=`http://127.0.0.1:${port}`;proc=startServer(port);await waitReady(base,proc);
    let response=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:temporary})}),body=await response.json();assert.equal(response.status,200);assert.equal(body.passwordChangeRequired,true);assert.ok(body.changeToken);
    response=await fetch(`${base}/api/auth/change-password-required`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({changeToken:body.changeToken,newPassword:fresh})});body=await response.json();assert.equal(response.status,200);assert.ok(body.user);let cookie=response.headers.get('set-cookie').split(';')[0],csrf=body.csrfToken;
    response=await fetch(`${base}/api/auth/mfa/setup`,{method:'POST',headers:{cookie,'x-csrf-token':csrf}});body=await response.json();assert.equal(response.status,200);assert.ok(body.secret);const secret=body.secret,code=totp.hotp(secret,Math.floor(Date.now()/1000/30));
    response=await fetch(`${base}/api/auth/mfa/enable`,{method:'POST',headers:{cookie,'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({code})});assert.equal(response.status,200);
    response=await fetch(`${base}/api/auth/logout`,{method:'POST',headers:{cookie,'x-csrf-token':csrf}});assert.equal(response.status,200);
    response=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:fresh})});body=await response.json();assert.equal(body.mfaRequired,true);assert.ok(body.mfaToken);
    response=await fetch(`${base}/api/auth/mfa`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mfaToken:body.mfaToken,code:totp.hotp(secret,Math.floor(Date.now()/1000/30))})});body=await response.json();assert.equal(response.status,200);assert.ok(body.user);assert.ok(response.headers.get('set-cookie'));
  }finally{if(proc)await stop(proc);await admin.query('DELETE FROM user_sessions WHERE user_id=$1',[id]).catch(()=>{});await admin.query('DELETE FROM auth_pending WHERE user_id=$1',[id]).catch(()=>{});await admin.query('DELETE FROM login_history WHERE user_id=$1',[id]).catch(()=>{});await admin.query('DELETE FROM app_users WHERE id=$1',[id]).catch(()=>{});await admin.end();}
});
