'use strict';
require('../backend/core/env').loadEnv();
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {Client}=require('pg');const {randomUUID}=require('node:crypto');
const workforce=require('../backend/infrastructure/database/repositories/org-workforce');const auth=require('../backend/infrastructure/database/repositories/auth');const permissions=require('../backend/core/permissions');
const dbTest=process.env.DATABASE_URL?test:test.skip;
async function rollback(fn){const c=new Client({connectionString:process.env.DATABASE_URL});await c.connect();try{await c.query('BEGIN');await c.query("SELECT set_config('app.is_system','on',true)");await fn(c);}finally{await c.query('ROLLBACK').catch(()=>{});await c.end();}}
async function actors(c){const owner=(await c.query(`SELECT * FROM app_users WHERE role='owner' LIMIT 1`)).rows[0],branch=(await c.query('SELECT * FROM branches WHERE id=$1',[owner.branch_id])).rows[0];const makerId=randomUUID();await c.query(`INSERT INTO app_users(id,username,password_hash,display_name,branch_id,role,branch_scope,must_change_password) VALUES($1,$2,'x','Org Maker',$3,'finance_manager','*',false)`,[makerId,`org-${Date.now()}`,owner.branch_id]);await c.query(`INSERT INTO user_role_assignments(id,user_id,role_code,scope_type,status,is_primary,reason,approved_by,approved_at) VALUES($1,$2,'finance_manager','GLOBAL','ACTIVE',true,'Wave 4 actor',$3,now())`,[randomUUID(),makerId,owner.id]);return{owner:{id:owner.id,role:'owner',branchId:owner.branch_id,branchScope:'*'},maker:{id:makerId,role:'finance_manager',branchId:owner.branch_id,branchScope:'*'},branch,legalEntityId:branch.legal_entity_id};}
const stamp=()=>`${Date.now().toString(36)}${Math.random().toString(36).slice(2,5)}`.toUpperCase();

test('Wave 4 Organization: migration memuat hierarchy version, Job, Position, Assignment, delegation, RLS, dan rollback',()=>{const root=path.join(__dirname,'..'),up=fs.readFileSync(path.join(root,'data/migrations/054_organization_workforce_foundation.sql'),'utf8'),down=fs.readFileSync(path.join(root,'data/migrations/054_organization_workforce_foundation.down.sql'),'utf8');for(const token of ['organization_hierarchy_versions','organization_jobs','organization_positions','position_assignments','authority_delegations','enforce_position_assignment_capacity','ENABLE ROW LEVEL SECURITY'])assert.match(up,new RegExp(token));assert.match(down,/DROP TABLE IF EXISTS authority_delegations/);});

dbTest('Wave 4 Organization: hierarchy snapshot publish memakai maker-checker dan immutable SHA',async()=>rollback(async c=>{const {owner,maker,legalEntityId}=await actors(c);const version=await workforce.captureVersion(c,maker,legalEntityId,{effectiveFrom:new Date().toISOString().slice(0,10),reason:'Publish struktur organisasi terkontrol'});assert.equal(version.status,'DRAFT');assert.equal(version.snapshotSha256.length,64);await workforce.decideVersion(c,maker,version.id,'submit');await assert.rejects(()=>workforce.decideVersion(c,maker,version.id,'approve','self approval'),e=>['PERMISSION_DENIED','SOD_CONFLICT'].includes(e.code));assert.equal((await workforce.decideVersion(c,owner,version.id,'approve','Owner approves hierarchy')).status,'APPROVED');assert.equal((await workforce.decideVersion(c,owner,version.id,'activate','Effective today')).status,'ACTIVE');}));

dbTest('Wave 4 Organization: Job→Position→Assignment menegakkan scope, SoD, headcount, dan overlap',async()=>rollback(async c=>{const {owner,maker,branch,legalEntityId}=await actors(c),s=stamp();const job=await workforce.createJob(c,maker,legalEntityId,{code:`J-${s}`,title:'Enterprise Controller',jobFamily:'FINANCE'});const position=await workforce.createPosition(c,maker,legalEntityId,{code:`P-${s}`,name:'Enterprise Controller',jobId:job.id,branchId:branch.id,headcount:1});const makeEmployee=async suffix=>(await c.query(`INSERT INTO employees(nik,name,department,job_title,base_salary,branch_id,join_date,active) VALUES($1,$2,'FINANCE','Candidate',0,$3,current_date,true) RETURNING *`,[`E-${s}${suffix}`,`Candidate ${suffix}`,branch.id])).rows[0];const first=await makeEmployee('A'),second=await makeEmployee('B');const proposed=await workforce.proposeAssignment(c,maker,{positionId:position.id,employeeId:first.id,effectiveFrom:new Date().toISOString().slice(0,10),reason:'Mengisi posisi controller utama'});await assert.rejects(()=>workforce.decideAssignment(c,maker,proposed.id,'approve','self'),e=>['PERMISSION_DENIED','SOD_CONFLICT'].includes(e.code));assert.equal((await workforce.decideAssignment(c,owner,proposed.id,'approve','Owner checker')).status,'ACTIVE');const overflow=await workforce.proposeAssignment(c,maker,{positionId:position.id,employeeId:second.id,effectiveFrom:new Date().toISOString().slice(0,10),reason:'Candidate headcount overflow'});await assert.rejects(()=>workforce.decideAssignment(c,owner,overflow.id,'approve','Capacity test'),e=>e.code==='23514');}));

dbTest('Wave 4 Organization: delegation berlaku runtime, scoped, time-bound, dan tidak dapat self-approve',async()=>rollback(async c=>{const {owner,maker}=await actors(c),delegate=(await c.query(`SELECT * FROM app_users WHERE role='sales' AND active LIMIT 1`)).rows[0];const from=new Date(Date.now()-60000).toISOString(),until=new Date(Date.now()+3600000).toISOString();const item=await workforce.proposeDelegation(c,maker,{delegateUserId:delegate.id,permissionCode:'invoice.approve',scopeType:'GLOBAL',effectiveFrom:from,effectiveUntil:until,reason:'Delegasi approval invoice saat cuti'});await assert.rejects(()=>workforce.decideDelegation(c,maker,item.id,'approve','self'),e=>['PERMISSION_DENIED','SOD_CONFLICT'].includes(e.code));assert.equal((await workforce.decideDelegation(c,owner,item.id,'approve','Owner checker')).status,'ACTIVE');const grants=await auth.delegatedGrantsForUser(c,delegate.id),user={id:delegate.id,role:'sales',delegatedGrants:grants};assert.equal(permissions.hasPermission(user,'invoice.approve'),true);assert.equal(permissions.hasPermission(user,'iam.approve'),false);await assert.rejects(()=>workforce.proposeDelegation(c,maker,{delegateUserId:delegate.id,permissionCode:'iam.approve',scopeType:'GLOBAL',effectiveFrom:from,effectiveUntil:until,reason:'Forbidden privilege escalation'}),e=>e.code==='PERMISSION_DENIED');}));
