'use strict';
const fs=require('node:fs/promises');
const path=require('node:path');
const {randomUUID,createHash}=require('node:crypto');
const {execFile}=require('node:child_process');
const {promisify}=require('node:util');
const {Client}=require('pg');
const runFile=promisify(execFile);
const ROOT=path.resolve(__dirname,'../../../storage/backups');
function connection(){const raw=process.env.MIGRATION_DATABASE_URL;if(!raw)throw new Error('MIGRATION_DATABASE_URL wajib untuk backup/restore.');return new URL(raw);}
async function executable(name){const configured=process.env[`PG_${name.toUpperCase()}_PATH`];const candidates=[configured,path.join(process.env.ProgramFiles||'C:\\Program Files','PostgreSQL','16','bin',`${name}.exe`),`${name}.exe`].filter(Boolean);for(const item of candidates){if(!path.isAbsolute(item))return item;try{await fs.access(item);return item;}catch{}}throw new Error(`${name} PostgreSQL 16 tidak ditemukan.`);}
function cli(url){return{host:url.hostname,port:url.port||'5432',user:decodeURIComponent(url.username),password:decodeURIComponent(url.password),database:decodeURIComponent(url.pathname.slice(1))};}
async function runBackup(client,{requestedBy=null}={}){
  await fs.mkdir(ROOT,{recursive:true});const id=randomUUID(),stamp=new Date().toISOString().replace(/[:.]/g,'-'),file=path.join(ROOT,`mat-erp-v2-${stamp}.dump`),url=connection(),cfg=cli(url);
  await client.query(`INSERT INTO backup_runs(id,target,backup_type,file_path,status) VALUES($1,'LOCAL_PRIVATE','FULL',$2,'RUNNING')`,[id,file]);
  try{const pgDump=await executable('pg_dump');await runFile(pgDump,['--format=custom','--compress=9','--no-owner','--no-acl','--host',cfg.host,'--port',cfg.port,'--username',cfg.user,'--file',file,cfg.database],{env:{...process.env,PGPASSWORD:cfg.password},windowsHide:true,maxBuffer:1024*1024});const bytes=await fs.readFile(file),checksum=createHash('sha256').update(bytes).digest('hex'),sizeMb=Math.max(1,Math.ceil(bytes.length/1048576));await client.query(`UPDATE backup_runs SET status='COMPLETED',finished_at=now(),size_mb=$2,checksum=$3 WHERE id=$1`,[id,sizeMb,checksum]);await prune(client);return{id,filePath:file,sizeBytes:bytes.length,checksum,requestedBy};}
  catch(error){await client.query(`UPDATE backup_runs SET status='FAILED',finished_at=now(),error=$2 WHERE id=$1`,[id,String(error.message).slice(0,2000)]);throw error;}
}
async function prune(client,keep=Number(process.env.MAT_BACKUP_RETAIN_COUNT||7)){keep=Math.min(Math.max(Number(keep)||7,2),60);const rows=(await client.query(`SELECT id,file_path FROM backup_runs WHERE status='COMPLETED' AND file_path IS NOT NULL ORDER BY finished_at DESC OFFSET $1`,[keep])).rows;for(const row of rows){const target=path.resolve(row.file_path);if(target.startsWith(ROOT+path.sep)){await fs.unlink(target).catch(error=>{if(error.code!=='ENOENT')throw error;});await client.query(`UPDATE backup_runs SET file_path=NULL,restore_test_detail=COALESCE(restore_test_detail,'')||' [File dipangkas oleh retention policy]' WHERE id=$1`,[row.id]);}}return rows.length;}
async function restoreDrill(client,{backupId,filePath}){
  const row=backupId?(await client.query(`SELECT * FROM backup_runs WHERE id=$1 AND status='COMPLETED'`,[backupId])).rows[0]:(await client.query(`SELECT * FROM backup_runs WHERE status='COMPLETED' ORDER BY finished_at DESC LIMIT 1`)).rows[0];if(!row)throw new Error('Backup completed tidak ditemukan.');const source=filePath||row.file_path;await fs.access(source);
  const suffix=randomUUID().replace(/-/g,'').slice(0,12),database=`mat_erp_restore_${suffix}`,url=connection(),adminUrl=new URL(url);adminUrl.pathname='/postgres';const admin=new Client({connectionString:adminUrl.toString(),application_name:'mat-erp-restore-drill'});let created=false;
  try{await admin.connect();await admin.query(`CREATE DATABASE ${database}`);created=true;const pgRestore=await executable('pg_restore'),cfg=cli(url);await runFile(pgRestore,['--no-owner','--no-acl','--exit-on-error','--host',cfg.host,'--port',cfg.port,'--username',cfg.user,'--dbname',database,source],{env:{...process.env,PGPASSWORD:cfg.password},windowsHide:true,maxBuffer:4*1024*1024});const restoredUrl=new URL(url);restoredUrl.pathname=`/${database}`;const probe=new Client({connectionString:restoredUrl.toString(),application_name:'mat-erp-restore-probe'});await probe.connect();const result=await probe.query(`SELECT count(*)::int tables FROM information_schema.tables WHERE table_schema='public'`);const migration=await probe.query(`SELECT filename FROM schema_migrations ORDER BY filename DESC LIMIT 1`);await probe.end();const detail={databaseTemporary:true,tables:result.rows[0].tables,latestMigration:migration.rows[0]?.filename};if(detail.tables<10)throw new Error('Restore drill menghasilkan schema yang tidak lengkap.');await client.query(`UPDATE backup_runs SET restore_tested=true,restore_tested_at=now(),restore_test_detail=$2 WHERE id=$1`,[row.id,JSON.stringify(detail)]);return{backupId:row.id,...detail};}
  catch(error){await client.query(`UPDATE backup_runs SET restore_tested=false,restore_tested_at=now(),restore_test_detail=$2 WHERE id=$1`,[row.id,String(error.message).slice(0,2000)]).catch(()=>{});throw error;}
  finally{if(created)await admin.query(`DROP DATABASE IF EXISTS ${database} WITH (FORCE)`).catch(()=>{});await admin.end().catch(()=>{});}
}
module.exports={ROOT,runBackup,restoreDrill,prune,executable};
