'use strict';
const { randomUUID } = require('node:crypto');
const { withTransaction } = require('../infrastructure/database/transaction');
const jobs = require('../infrastructure/database/repositories/operations');
const artifacts = require('../infrastructure/files/artifact-storage');
const backup = require('../infrastructure/database/backup');
const privateStorage = require('../infrastructure/files/private-storage');
const businessOps = require('../infrastructure/database/repositories/business-operations');
const {parse:parseCsv}=require('../core/csv');
async function scheduleBackup(client){if(process.env.MAT_BACKUP_SCHEDULE_ENABLED==='0')return false;const active=Number((await client.query(`SELECT count(*) n FROM background_jobs WHERE job_type='BACKUP_RUN' AND status IN('QUEUED','PROCESSING')`)).rows[0].n);if(active)return false;const latest=(await client.query(`SELECT finished_at FROM backup_runs WHERE status='COMPLETED' ORDER BY finished_at DESC LIMIT 1`)).rows[0],hours=Math.min(Math.max(Number(process.env.MAT_BACKUP_INTERVAL_HOURS)||24,1),168);if(latest&&Date.now()-new Date(latest.finished_at).getTime()<hours*3600000)return false;const owner=(await client.query(`SELECT id,role FROM app_users WHERE role='owner' AND active ORDER BY created_at LIMIT 1`)).rows[0];if(!owner)return false;await jobs.enqueue(client,{type:'BACKUP_RUN',user:owner,params:{scheduled:true}});return true;}
async function execute(client,job){
  const params=job.params||{};let title=String(params.title||job.label||'MAT ERP').slice(0,120),rows=Array.isArray(params.rows)?params.rows:[];
  if(params.documentNumber){const document=(await client.query(`SELECT document_number,title,document_type,status,amount,party_name,due_date FROM business_documents WHERE document_number=$1`,[params.documentNumber])).rows[0];if(document){title=`${document.document_number} - ${document.title}`;rows=[document,...(await client.query(`SELECT line_no,description,qty,uom,unit_price,line_total FROM document_lines WHERE document_id=(SELECT id FROM business_documents WHERE document_number=$1) ORDER BY line_no`,[params.documentNumber])).rows];}}
  if(params.type&&!rows.length){rows=(await client.query(`SELECT document_number,title,status,amount,party_name,due_date,updated_at FROM business_documents WHERE document_type=$1 AND NOT is_archived ORDER BY updated_at DESC LIMIT 5000`,[params.type])).rows;title=`Ekspor ${params.type}`;}
  if(params.report&&!rows.length){rows=await reportRows(client,params.report);title=params.report;}
  if(job.jobType==='GENERATE_PDF'){const artifact=await artifacts.create(client,{job,kind:'pdf',title,rows});return{ok:true,artifactId:artifact.id,fileName:artifact.fileName,sizeBytes:artifact.sizeBytes};}
  if(job.jobType==='PAYROLL_SLIPS'){if(!params.documentId)throw new Error('documentId wajib untuk slip payroll.');const user=await workerUser(client,job.requestedBy),items=await businessOps.payrollItems(client,params.documentId,user),doc=(await client.query('SELECT document_number,title FROM business_documents WHERE id=$1',[params.documentId])).rows[0];const artifact=await artifacts.create(client,{job,kind:'pdf',title:`Slip-${doc?.document_number||'Payroll'}`,rows:items.map(x=>({Karyawan:x.employeeName,GajiPokok:Number(x.baseSalary),Tunjangan:Number(x.allowances),Lembur:Number(x.overtime),Potongan:Number(x.deductions),BPJS:Number(x.bpjsEmployee),PPh21:Number(x.pph21),GajiBersih:Number(x.netPay)}))});return{ok:true,artifactId:artifact.id,fileName:artifact.fileName,sizeBytes:artifact.sizeBytes,slips:items.length};}
  if(['EXPORT_EXCEL','REPORT_GENERATE'].includes(job.jobType)){const artifact=await artifacts.create(client,{job,kind:'excel',title,rows});return{ok:true,artifactId:artifact.id,fileName:artifact.fileName,sizeBytes:artifact.sizeBytes};}
  if(job.jobType==='NOTIFICATION_SEND'){const notification=await jobs.notify(client,{userId:params.userId||job.requestedBy,role:params.role,category:params.category||'INFORMATION',title,body:params.body||'',link:params.link,dedupeKey:params.dedupeKey});if(notification){await client.query(`INSERT INTO notification_deliveries(notification_id,channel,status,attempts,sent_at) VALUES($1,'IN_APP','SENT',1,now())`,[notification.id]);if(params.email)await client.query(`INSERT INTO notification_deliveries(notification_id,channel,destination,status,last_error) VALUES($1,'EMAIL',$2,'SKIPPED','SMTP belum dikonfigurasi')`,[notification.id,String(params.email).slice(0,240)]);if(params.webhook)await client.query(`INSERT INTO notification_deliveries(notification_id,channel,destination,status,last_error) VALUES($1,'WEBHOOK',$2,'SKIPPED','Webhook outbound dinonaktifkan pada development')`,[notification.id,String(params.webhook).slice(0,240)]);}return{ok:true,notificationId:notification?.id||null,deduplicated:!notification};}
  if(job.jobType==='BACKUP_RUN'){const result=await backup.runBackup(client,{requestedBy:job.requestedBy});return{ok:true,backupId:result.id,sizeBytes:result.sizeBytes,checksum:result.checksum};}
  if(job.jobType==='IMPORT_CSV')return importCsv(client,job,params);
  if(job.jobType==='RECONCILIATION'){const user=await workerUser(client,job.requestedBy),result=await businessOps.reconcile(client,{period:params.period,branchId:params.branchId,user});return{ok:true,reconciliationId:result.id,matchedCount:result.matchedCount,difference:Number(result.difference)};}
  return{ok:true,jobType:job.jobType,processedAt:new Date().toISOString(),note:'Executor khusus tidak diperlukan.'};
}
async function reportRows(client,name){
  if(name==='Penjualan per pelanggan')return(await client.query(`SELECT COALESCE(party_name,'Tanpa pelanggan') pelanggan,count(*)::int dokumen,sum(amount)::float nilai FROM business_documents WHERE document_type IN('QUOTATION','SALES_ORDER','INVOICE') AND status NOT IN('CANCELLED','VOID','REJECTED') GROUP BY party_name ORDER BY nilai DESC`)).rows;
  if(name==='AR & AP aging')return(await client.query(`SELECT document_number dokumen,document_type jenis,party_name relasi,amount::float nilai,due_date jatuh_tempo,GREATEST(current_date-COALESCE(due_date,current_date),0)::int umur_hari,status FROM business_documents WHERE document_type IN('INVOICE','SUPPLIER_INVOICE') AND status NOT IN('CLOSED','CANCELLED','VOID','REJECTED') ORDER BY due_date NULLS LAST`)).rows;
  if(name==='Profitabilitas proyek')return(await client.query(`SELECT document_number proyek,title,party_name pelanggan,amount::float nilai,COALESCE((payload->>'estimatedCost')::numeric,0)::float estimasi_biaya,(amount-COALESCE((payload->>'estimatedCost')::numeric,0))::float margin,status FROM business_documents WHERE document_type='PROJECT' AND status NOT IN('CANCELLED','VOID') ORDER BY updated_at DESC`)).rows;
  if(name==='Kinerja produksi')return(await client.query(`SELECT document_number work_order,title,party_name pelanggan,COALESCE((payload->>'progress')::numeric,0)::float progres,COALESCE(payload->>'stage','Belum ditentukan') tahap,due_date jatuh_tempo,status FROM business_documents WHERE document_type='WORK_ORDER' AND status NOT IN('CANCELLED','VOID') ORDER BY updated_at DESC`)).rows;
  if(name==='Mutasi persediaan')return(await client.query(`SELECT m.created_at waktu,p.code sku,p.name produk,b.name gudang,m.movement_type jenis,m.qty::float qty,m.unit_cost::float harga_pokok,d.document_number dokumen FROM inventory_movements m JOIN products p ON p.id=m.product_id JOIN branches b ON b.id=m.warehouse_id JOIN business_documents d ON d.id=m.document_id ORDER BY m.created_at DESC LIMIT 5000`)).rows;
  if(name==='Rekap payroll & BPJS')return(await client.query(`SELECT d.document_number payroll,d.payload->>'period' periode,e.nik,e.name karyawan,p.base_salary::float gaji_pokok,p.allowances::float tunjangan,p.overtime::float lembur,p.deductions::float potongan,(p.bpjs_company+p.bpjs_employee)::float bpjs,p.pph21::float pph21,p.net_pay::float gaji_bersih,d.status FROM payroll_items p JOIN business_documents d ON d.id=p.payroll_document_id JOIN employees e ON e.id=p.employee_id ORDER BY d.payload->>'period' DESC,e.name`)).rows;
  return[];
}
async function workerUser(client,id){const row=(await client.query(`SELECT id,username,display_name "displayName",role,branch_id "branchId",branch_scope "branchScope",employee_id "employeeId" FROM app_users WHERE id=$1 AND active`,[id])).rows[0];if(!row)throw new Error('Pemohon job tidak aktif.');return row;}
async function importCsv(client,job,params){const user=await workerUser(client,job.requestedBy),module=String(params.module||''),allowed=new Set(['attendance','customers','suppliers','products','employees','bank']);if(!allowed.has(module))throw new Error('Modul import tidak didukung.');let text=params.csvText,fileName=params.fileName||'import.csv';if(params.fileId){const file=await privateStorage.download(client,params.fileId);text=file.buffer.toString('utf8');fileName=file.item.originalFilename;}const rows=parseCsv(text),errors=[];let success=0;for(const row of rows){try{if(module==='attendance'){const employee=(await client.query('SELECT id FROM employees WHERE nik=$1',[row.nik])).rows[0];if(!employee)throw new Error(`NIK ${row.nik} tidak ditemukan`);await businessOps.upsertAttendance(client,{employeeId:employee.id,workDate:row.work_date,checkIn:row.check_in||null,checkOut:row.check_out||null,status:row.status||'PRESENT',notes:row.notes,user,source:'CSV'});}else if(module==='bank'){const direction=String(row.direction||'').toUpperCase();await client.query(`INSERT INTO bank_transactions(id,branch_id,transaction_date,reference,description,direction,amount,imported_by) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7) ON CONFLICT(branch_id,reference,direction) DO NOTHING`,[user.branchId,row.transaction_date,row.reference,row.description||null,direction,Number(row.amount),user.id]);}else{const ops=require('../infrastructure/database/repositories/operations'),key={customers:'code',suppliers:'code',products:'code',employees:'nik'}[module],existing=(await client.query(`SELECT id FROM ${module} WHERE ${key}=$1`,[row[key]])).rows[0],body={...row};delete body.line;if(existing)await ops.updateMaster(client,module,existing.id,body,user);else await ops.createMaster(client,module,body,user);}success++;}catch(error){errors.push({line:row.line,message:String(error.message).slice(0,240)});}}const batch=(await client.query(`INSERT INTO import_batches(job_id,module,file_name,total_rows,success_rows,error_rows,errors,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[job.id,module,fileName,rows.length,success,errors.length,JSON.stringify(errors.slice(0,100)),user.id])).rows[0];if(!success&&errors.length)throw new Error(`Seluruh ${errors.length} baris gagal diimpor.`);return{ok:true,batchId:batch.id,totalRows:rows.length,successRows:success,errorRows:errors.length,errors:errors.slice(0,10)};}
// Maintenance partisi audit: pastikan partisi tahun berjalan + 1 selalu ada
// (fungsi SECURITY DEFINER dari migrasi 011). Dipanggil maksimal 2×/hari.
async function auditPartitionMaintenance(client){
  const created=(await client.query('SELECT audit_partition_maintenance() AS created')).rows[0].created;
  if(created&&created.length)console.log(JSON.stringify({level:'info',service:'job-worker',message:`Partisi audit dibuat: ${created.join(', ')}`,at:new Date().toISOString()}));
  return created;
}
function start({pollMs=1000}={}) {
  const workerId=`mat-worker-${process.pid}-${randomUUID().slice(0,8)}`;let stopped=false,running=false,timer,lastSchedule=0,lastMaintenance=0;
  const schedule=()=>{if(!stopped)timer=setTimeout(tick,pollMs).unref();};
  const tick=async()=>{if(running||stopped)return schedule();running=true;try{
    await withTransaction(c=>jobs.recoverExpired(c));if(Date.now()-lastSchedule>60000){await withTransaction(scheduleBackup);lastSchedule=Date.now();}
    if(Date.now()-lastMaintenance>12*3600000){await withTransaction(auditPartitionMaintenance).catch(error=>{console.error(JSON.stringify({level:'error',service:'job-worker',message:`Maintenance partisi audit gagal: ${error.message}`,at:new Date().toISOString()}));require('../infrastructure/alerts').send('Maintenance partisi audit gagal',error.message).catch(()=>{});});lastMaintenance=Date.now();}
    const job=await withTransaction(c=>jobs.claim(c,workerId,{leaseSeconds:60}));
    if(job){try{const result=await withTransaction(c=>execute(c,job));await withTransaction(async c=>{await jobs.complete(c,job.id,workerId,result);await jobs.notify(c,{userId:job.requestedBy,category:'SUCCESS',title:`${job.label} selesai`,body:result.fileName?`${result.fileName} siap diunduh.`:'Proses latar belakang selesai.',link:'#/system/jobs',dedupeKey:`job:${job.id}:completed`});});}catch(error){await withTransaction(async c=>{await jobs.fail(c,job.id,workerId,error.message);await jobs.notify(c,{userId:job.requestedBy,category:'WARNING',title:`${job.label} gagal`,body:String(error.message).slice(0,500),link:'#/system/jobs',dedupeKey:`job:${job.id}:failed`});});}}
  }catch(error){console.error(JSON.stringify({level:'error',service:'job-worker',workerId,error:error.message,at:new Date().toISOString()}));}finally{running=false;schedule();}};
  tick();return{workerId,stop(){stopped=true;if(timer)clearTimeout(timer);}};
}
module.exports={start,execute,scheduleBackup};
