'use strict';
const {randomUUID}=require('node:crypto');
const {AppError}=require('../../../core/errors');
const {grantsFor}=require('../../../core/permissions');
const {camel}=require('./runtime');

const SCOPES=new Set(['GLOBAL','LEGAL_ENTITY','BUSINESS_UNIT','BRANCH','PLANT','WAREHOUSE','DEPARTMENT','PROJECT','OWN_RECORD']);
const LEVELS=new Set(['supervisor','finance','owner']);

async function listRoles(client){
  const rows=(await client.query(`SELECT r.*,
    (SELECT count(*)::int FROM user_role_assignments a WHERE a.role_code=r.code AND a.status='ACTIVE' AND (a.effective_until IS NULL OR a.effective_until>now())) assigned_count
    FROM enterprise_roles r WHERE r.active ORDER BY CASE category WHEN 'EXECUTIVE' THEN 0 WHEN 'PLATFORM' THEN 1 WHEN 'CONTROL' THEN 2 WHEN 'BUSINESS' THEN 3 ELSE 4 END,name`)).rows;
  return rows.map(row=>({...camel(row),permissions:[...grantsFor(row.code)]}));
}

async function listAssignments(client,{status,userId}={}){const params=[];let where='TRUE';if(status){params.push(status);where+=` AND a.status=$${params.length}`;}if(userId){params.push(userId);where+=` AND a.user_id=$${params.length}`;}return(await client.query(`SELECT a.*,u.username,u.display_name,r.name role_name,requester.display_name requested_by_name,approver.display_name approved_by_name
  FROM user_role_assignments a JOIN app_users u ON u.id=a.user_id JOIN enterprise_roles r ON r.code=a.role_code
  LEFT JOIN app_users requester ON requester.id=a.requested_by LEFT JOIN app_users approver ON approver.id=a.approved_by
  WHERE ${where} ORDER BY a.created_at DESC LIMIT 300`,params)).rows.map(camel);}

async function requestAssignment(client,{targetUserId,roleCode,scopeType='BRANCH',scopeId,effectiveUntil,reason,isPrimary=true,user}){
  if(!reason)throw new AppError('REASON_REQUIRED');if(!SCOPES.has(scopeType))throw new AppError('VALIDATION_ERROR','Data scope tidak dikenal.');
  if(isPrimary===false)throw new AppError('VALIDATION_ERROR','Runtime saat ini memakai tepat satu primary role; additional role tidak dapat diaktifkan.');
  const target=(await client.query('SELECT id,role,branch_id FROM app_users WHERE id=$1',[targetUserId])).rows[0];if(!target)throw new AppError('RESOURCE_NOT_FOUND','Pengguna tidak ditemukan.');
  const role=(await client.query('SELECT * FROM enterprise_roles WHERE code=$1 AND active',[roleCode])).rows[0];if(!role)throw new AppError('VALIDATION_ERROR','Role enterprise tidak dikenal.');
  if(roleCode==='owner'&&user.role!=='owner')throw new AppError('PERMISSION_DENIED','Hanya Owner dapat mengusulkan role Owner.');
  if(scopeType==='BRANCH'&&!scopeId)scopeId=target.branch_id;if(scopeType==='GLOBAL'&&scopeId)throw new AppError('VALIDATION_ERROR','GLOBAL tidak menggunakan scopeId.');
  if(effectiveUntil&&new Date(effectiveUntil)<=new Date())throw new AppError('VALIDATION_ERROR','Masa berlaku assignment harus di masa depan.');
  const existing=(await client.query(`SELECT id FROM user_role_assignments WHERE user_id=$1 AND role_code=$2 AND status IN('PENDING','ACTIVE') AND is_primary=$3`,[targetUserId,roleCode,!!isPrimary])).rows[0];if(existing)throw new AppError('DUPLICATE_REQUEST','Assignment role yang sama masih aktif atau menunggu approval.');
  return camel((await client.query(`INSERT INTO user_role_assignments(id,user_id,role_code,scope_type,scope_id,status,is_primary,effective_until,reason,requested_by)
    VALUES($1,$2,$3,$4,$5,'PENDING',$6,$7,$8,$9) RETURNING *`,[randomUUID(),targetUserId,roleCode,scopeType,scopeId||null,!!isPrimary,effectiveUntil||null,String(reason).slice(0,1000),user.id])).rows[0]);
}

async function roleConflicts(client,userId,newRole,excludeAssignment){return(await client.query(`SELECT r.* FROM sod_rules r JOIN user_role_assignments a ON a.user_id=$1 AND a.status='ACTIVE' AND (a.effective_until IS NULL OR a.effective_until>now())
  WHERE r.active AND r.rule_type='ROLE_CONFLICT' AND a.id<>COALESCE($3::uuid,'00000000-0000-0000-0000-000000000000'::uuid)
  AND ((r.left_role=$2 AND r.right_role=a.role_code) OR (r.right_role=$2 AND r.left_role=a.role_code))`,[userId,newRole,excludeAssignment||null])).rows.map(camel);}

async function decideAssignment(client,id,{approve,reason,user}){
  if(!reason)throw new AppError('REASON_REQUIRED');const row=(await client.query(`SELECT * FROM user_role_assignments WHERE id=$1 AND status='PENDING' FOR UPDATE`,[id])).rows[0];if(!row)throw new AppError('RESOURCE_NOT_FOUND','Assignment pending tidak ditemukan.');if(row.requested_by===user.id)throw new AppError('SOD_CONFLICT','Pengusul role tidak boleh menyetujui usulannya sendiri.');
  if(!approve)return camel((await client.query(`UPDATE user_role_assignments SET status='REJECTED',approved_by=$2,approved_at=now(),revoke_reason=$3 WHERE id=$1 RETURNING *`,[id,user.id,String(reason).slice(0,1000)])).rows[0]);
  const conflicts=await roleConflicts(client,row.user_id,row.role_code,row.id);if(conflicts.length){for(const rule of conflicts)await client.query(`INSERT INTO sod_conflict_events(rule_id,user_id,assignment_id,status,detail) VALUES($1,$2,$3,'BLOCKED',$4)`,[rule.id,row.user_id,row.id,{roleCode:row.role_code,reason}]);await client.query(`UPDATE user_role_assignments SET status='REJECTED',approved_by=$2,approved_at=now(),revoke_reason='SoD conflict' WHERE id=$1`,[id,user.id]);return{blocked:true,conflicts};}
  if(row.is_primary){await client.query(`UPDATE user_role_assignments SET status='REVOKED',revoked_by=$2,revoked_at=now(),revoke_reason='Digantikan assignment primary baru' WHERE user_id=$1 AND status='ACTIVE' AND is_primary`,[row.user_id,user.id]);const branchScope=row.scope_type==='GLOBAL'?'*':null,branchId=row.scope_type==='BRANCH'?row.scope_id:null;await client.query(`UPDATE app_users SET role=$2,branch_scope=$3,branch_id=COALESCE($4,branch_id),active=true,updated_at=now() WHERE id=$1`,[row.user_id,row.role_code,branchScope,branchId]);}
  const approved=camel((await client.query(`UPDATE user_role_assignments SET status='ACTIVE',approved_by=$2,approved_at=now() WHERE id=$1 RETURNING *`,[id,user.id])).rows[0]);await client.query("UPDATE user_sessions SET active=false,ended_at=now(),end_reason='access_changed' WHERE user_id=$1 AND active",[row.user_id]);return approved;
}

async function revokeAssignment(client,id,{reason,user}){if(!reason)throw new AppError('REASON_REQUIRED');const row=(await client.query(`UPDATE user_role_assignments SET status='REVOKED',revoked_by=$2,revoked_at=now(),revoke_reason=$3 WHERE id=$1 AND status='ACTIVE' RETURNING *`,[id,user.id,String(reason).slice(0,1000)])).rows[0];if(!row)throw new AppError('RESOURCE_NOT_FOUND','Assignment aktif tidak ditemukan.');if(row.is_primary)await client.query('UPDATE app_users SET active=false,updated_at=now() WHERE id=$1',[row.user_id]);await client.query("UPDATE user_sessions SET active=false,ended_at=now(),end_reason='access_revoked' WHERE user_id=$1 AND active",[row.user_id]);return camel(row);}

async function listSod(client){const rules=(await client.query(`SELECT * FROM sod_rules WHERE active ORDER BY severity DESC,code`)).rows.map(camel),conflicts=(await client.query(`SELECT c.*,r.code rule_code,r.name rule_name,u.display_name user_name FROM sod_conflict_events c JOIN sod_rules r ON r.id=c.rule_id LEFT JOIN app_users u ON u.id=c.user_id ORDER BY c.detected_at DESC LIMIT 100`)).rows.map(camel);return{rules,conflicts};}

async function createOverride(client,{targetUserId,permissionCode,scopeType='GLOBAL',scopeId,hours=1,reason,user}){if(user.role!=='owner')throw new AppError('PERMISSION_DENIED','Emergency override hanya dapat diberikan Owner.');if(!reason)throw new AppError('REASON_REQUIRED');hours=Number(hours);if(!(hours>0&&hours<=24))throw new AppError('VALIDATION_ERROR','Emergency override maksimal 24 jam.');if(!SCOPES.has(scopeType))throw new AppError('VALIDATION_ERROR','Scope tidak valid.');const valid=(await client.query('SELECT 1 FROM permission_catalog WHERE code=$1 AND active',[permissionCode])).rowCount;if(!valid)throw new AppError('VALIDATION_ERROR','Permission tidak dikenal.');return camel((await client.query(`INSERT INTO emergency_access_overrides(id,user_id,permission_code,scope_type,scope_id,reason,effective_until,granted_by) VALUES($1,$2,$3,$4,$5,$6,now()+($7||' hours')::interval,$8) RETURNING *`,[randomUUID(),targetUserId,permissionCode,scopeType,scopeId||null,String(reason).slice(0,1000),String(hours),user.id])).rows[0]);}
async function listOverrides(client){await client.query(`UPDATE emergency_access_overrides SET status='EXPIRED' WHERE status='ACTIVE' AND effective_until<=now()`);return(await client.query(`SELECT o.*,u.display_name user_name,g.display_name granted_by_name FROM emergency_access_overrides o JOIN app_users u ON u.id=o.user_id JOIN app_users g ON g.id=o.granted_by ORDER BY o.created_at DESC LIMIT 100`)).rows.map(camel);}

function normalizeSteps(steps){if(!Array.isArray(steps)||!steps.length)throw new AppError('VALIDATION_ERROR','Minimal satu approval step wajib diisi.');const levels=steps.map(x=>typeof x==='string'?x:x.level);if(levels.some(x=>!LEVELS.has(x))||new Set(levels).size!==levels.length)throw new AppError('VALIDATION_ERROR','Approval step tidak valid atau duplikat.');return levels.map((level,index)=>({level,sequence:index+1,allowOverride:level!=='owner'}));}
async function listPolicies(client){return(await client.query(`SELECT p.*,b.name branch_name,c.display_name created_by_name,a.display_name activated_by_name FROM approval_policy_versions p LEFT JOIN branches b ON b.id=p.branch_id LEFT JOIN app_users c ON c.id=p.created_by LEFT JOIN app_users a ON a.id=p.activated_by ORDER BY p.policy_key,p.version DESC`)).rows.map(camel);}
async function createPolicy(client,body,user){if(!body.changeReason)throw new AppError('REASON_REQUIRED');const key=String(body.policyKey||'').toUpperCase();if(!/^[A-Z0-9_-]{3,80}$/.test(key))throw new AppError('VALIDATION_ERROR','Policy key hanya A-Z, angka, _ dan -.');const min=Number(body.minAmount||0),max=body.maxAmount===null||body.maxAmount===''?null:Number(body.maxAmount);if(min<0||(max!==null&&max<min))throw new AppError('VALIDATION_ERROR','Rentang nominal policy tidak valid.');const version=Number((await client.query('SELECT COALESCE(max(version),0)+1 n FROM approval_policy_versions WHERE policy_key=$1',[key])).rows[0].n);return camel((await client.query(`INSERT INTO approval_policy_versions(id,policy_key,version,document_type,branch_id,min_amount,max_amount,steps,status,effective_from,effective_until,change_reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'DRAFT',$9,$10,$11,$12) RETURNING *`,[randomUUID(),key,version,body.documentType||'*',body.branchId||null,min,max,normalizeSteps(body.steps),body.effectiveFrom||new Date(),body.effectiveUntil||null,String(body.changeReason).slice(0,1000),user.id])).rows[0]);}
async function activatePolicy(client,id,{reason,user}){if(!reason)throw new AppError('REASON_REQUIRED');const row=(await client.query(`SELECT * FROM approval_policy_versions WHERE id=$1 AND status='DRAFT' FOR UPDATE`,[id])).rows[0];if(!row)throw new AppError('RESOURCE_NOT_FOUND','Draft approval policy tidak ditemukan.');if(row.created_by===user.id)throw new AppError('SOD_CONFLICT','Pembuat policy tidak boleh mengaktifkan versinya sendiri.');const overlap=(await client.query(`SELECT id,policy_key FROM approval_policy_versions WHERE status='ACTIVE' AND id<>$1 AND document_type=$2 AND branch_id IS NOT DISTINCT FROM $3 AND effective_from<COALESCE($5,'infinity') AND COALESCE(effective_until,'infinity')>$4 AND min_amount<=COALESCE($7,1e30) AND COALESCE(max_amount,1e30)>=$6`,[id,row.document_type,row.branch_id,row.effective_from,row.effective_until,row.min_amount,row.max_amount])).rows;if(overlap.length)throw new AppError('DOCUMENT_CONFLICT',`Policy overlap dengan ${overlap.map(x=>x.policy_key).join(', ')}.`);await client.query(`UPDATE approval_policy_versions SET status='RETIRED',effective_until=now() WHERE policy_key=$1 AND status='ACTIVE'`,[row.policy_key]);return camel((await client.query(`UPDATE approval_policy_versions SET status='ACTIVE',activated_by=$2,activated_at=now(),change_reason=change_reason||E'\nAktivasi: '||$3 WHERE id=$1 RETURNING *`,[id,user.id,String(reason).slice(0,500)])).rows[0]);}
async function resolvePolicy(client,{documentType,branchId,amount}){const row=(await client.query(`SELECT * FROM approval_policy_versions WHERE status='ACTIVE' AND document_type IN($1,'*') AND (branch_id IS NULL OR branch_id=$2) AND min_amount<=$3 AND (max_amount IS NULL OR max_amount>=$3) AND effective_from<=now() AND (effective_until IS NULL OR effective_until>now()) ORDER BY (document_type=$1) DESC,(branch_id=$2) DESC,min_amount DESC,version DESC LIMIT 1`,[documentType,branchId,Number(amount)])).rows[0];if(!row)throw new AppError('RESOURCE_NOT_FOUND','Approval policy aktif tidak ditemukan untuk dokumen ini.');return{policy:camel(row),levels:(row.steps||[]).sort((a,b)=>a.sequence-b.sequence).map(x=>x.level),snapshot:{policyId:row.id,policyKey:row.policy_key,version:row.version,documentType:row.document_type,branchId:row.branch_id,minAmount:Number(row.min_amount),maxAmount:row.max_amount===null?null:Number(row.max_amount),steps:row.steps,resolvedAt:new Date().toISOString()}};}

async function listReviews(client){return(await client.query(`SELECT r.*,u.display_name created_by_name,(SELECT count(*)::int FROM access_review_items i WHERE i.review_id=r.id) total_items,(SELECT count(*)::int FROM access_review_items i WHERE i.review_id=r.id AND i.decision='PENDING') pending_items FROM access_reviews r JOIN app_users u ON u.id=r.created_by ORDER BY r.created_at DESC`)).rows.map(camel);}
async function createReview(client,{title,scopeType='GLOBAL',scopeId,dueAt,user}){if(!title||!SCOPES.has(scopeType))throw new AppError('VALIDATION_ERROR','Judul dan scope review wajib valid.');if(!dueAt||new Date(dueAt)<=new Date())throw new AppError('VALIDATION_ERROR','Due date access review harus di masa depan.');const review=(await client.query(`INSERT INTO access_reviews(id,title,scope_type,scope_id,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[randomUUID(),String(title).slice(0,160),scopeType,scopeId||null,dueAt,user.id])).rows[0];await client.query(`INSERT INTO access_review_items(id,review_id,assignment_id) SELECT gen_random_uuid(),$1,id FROM user_role_assignments WHERE status='ACTIVE' AND (effective_until IS NULL OR effective_until>now()) AND ($2='GLOBAL' OR scope_type=$2 AND scope_id IS NOT DISTINCT FROM $3)`,[review.id,scopeType,scopeId||null]);return camel(review);}
async function reviewDetail(client,id){const review=camel((await client.query('SELECT * FROM access_reviews WHERE id=$1',[id])).rows[0]);if(!review)throw new AppError('RESOURCE_NOT_FOUND');review.items=(await client.query(`SELECT i.*,a.user_id,a.role_code,a.scope_type,a.scope_id,u.display_name user_name FROM access_review_items i JOIN user_role_assignments a ON a.id=i.assignment_id JOIN app_users u ON u.id=a.user_id WHERE i.review_id=$1 ORDER BY u.display_name`,[id])).rows.map(camel);return review;}
async function decideReviewItem(client,itemId,{decision,reason,user}){if(!['RETAIN','REVOKE'].includes(decision)||!reason)throw new AppError('VALIDATION_ERROR','Decision dan alasan wajib diisi.');const item=(await client.query(`UPDATE access_review_items SET decision=$2,reason=$3,decided_by=$4,decided_at=now() WHERE id=$1 AND decision='PENDING' RETURNING *`,[itemId,decision,String(reason).slice(0,1000),user.id])).rows[0];if(!item)throw new AppError('RESOURCE_NOT_FOUND');if(decision==='REVOKE')await revokeAssignment(client,item.assignment_id,{reason:`Access review: ${reason}`,user});return camel(item);}
async function completeReview(client,id,{user}){const pending=Number((await client.query(`SELECT count(*) n FROM access_review_items WHERE review_id=$1 AND decision='PENDING'`,[id])).rows[0].n);if(pending)throw new AppError('VALIDATION_ERROR',`${pending} item access review belum diputuskan.`);const row=(await client.query(`UPDATE access_reviews SET status='COMPLETED',completed_by=$2,completed_at=now() WHERE id=$1 AND status='OPEN' RETURNING *`,[id,user.id])).rows[0];if(!row)throw new AppError('RESOURCE_NOT_FOUND');return camel(row);}

module.exports={SCOPES,listRoles,listAssignments,requestAssignment,roleConflicts,decideAssignment,revokeAssignment,listSod,createOverride,listOverrides,listPolicies,createPolicy,activatePolicy,resolvePolicy,listReviews,createReview,reviewDetail,decideReviewItem,completeReview,normalizeSteps};
