'use strict';
const {randomUUID}=require('node:crypto');const {AppError}=require('../../../core/errors');const {camel}=require('./runtime');
const CATEGORIES=new Set(['ACTION_REQUIRED','WARNING','INFORMATION','SUCCESS','SYSTEM_ALERT']);
const JOBS={GENERATE_PDF:{priority:'medium',label:'Pembuatan PDF'},PAYROLL_SLIPS:{priority:'medium',label:'Slip gaji massal'},EXPORT_EXCEL:{priority:'low',label:'Ekspor Excel',limit:2},IMPORT_CSV:{priority:'low',label:'Impor CSV',limit:1},IMAGE_COMPRESS:{priority:'low',label:'Kompresi gambar',limit:2},REPORT_GENERATE:{priority:'medium',label:'Pembuatan laporan'},NOTIFICATION_SEND:{priority:'high',label:'Pengiriman notifikasi'},BACKUP_RUN:{priority:'low',label:'Backup terjadwal'},ARCHIVE_RUN:{priority:'low',label:'Arsip data lama'},RECONCILIATION:{priority:'low',label:'Rekonsiliasi besar'}};

async function notify(client,{userId,role,category,title,body,link,dedupeKey}){
  const id=randomUUID();const result=await client.query(`INSERT INTO notifications(id,user_id,target_role,category,title,body,link,dedupe_key)
    VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING RETURNING *`,[id,userId||null,role||null,CATEGORIES.has(category)?category:'INFORMATION',title,body||'',link||null,dedupeKey||null]);
  return camel(result.rows[0]);
}
async function listNotifications(client,user,{limit=60}={}){return (await client.query(`SELECT * FROM notifications WHERE user_id=$1 OR target_role IN($2,'*') ORDER BY created_at DESC LIMIT $3`,[user.id,user.role,Math.min(limit,100)])).rows.map(camel);}
async function unreadCount(client,user){return Number((await client.query(`SELECT count(*) n FROM notifications WHERE read_at IS NULL AND (user_id=$1 OR target_role IN($2,'*'))`,[user.id,user.role])).rows[0].n);}
async function markRead(client,user,id){return (await client.query(`UPDATE notifications SET read_at=now() WHERE id=$1 AND (user_id=$2 OR target_role IN($3,'*')) RETURNING id`,[id,user.id,user.role])).rowCount>0;}
async function markAllRead(client,user){return (await client.query(`UPDATE notifications SET read_at=now() WHERE read_at IS NULL AND (user_id=$1 OR target_role IN($2,'*'))`,[user.id,user.role])).rowCount;}

async function enqueue(client,{type,user,params={}}){
  const spec=JOBS[type];if(!spec)throw new AppError('VALIDATION_ERROR',`Tipe job '${type}' tidak dikenal.`);
  await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`job:${user.id}:${type}`]);
  if(spec.limit){const active=Number((await client.query(`SELECT count(*) n FROM background_jobs WHERE requested_by=$1 AND job_type=$2 AND status IN('QUEUED','PROCESSING')`,[user.id,type])).rows[0].n);if(active>=spec.limit)throw new AppError('JOB_LIMIT',`Maksimal ${spec.limit} job '${spec.label}' aktif.`);}
  return camel((await client.query(`INSERT INTO background_jobs(id,job_type,label,priority,params,status,requested_by) VALUES($1,$2,$3,$4,$5,'QUEUED',$6) RETURNING *`,[randomUUID(),type,spec.label,spec.priority,params,user.id])).rows[0]);
}
async function claim(client,workerId,{leaseSeconds=60}={}){
  const result=await client.query(`WITH candidate AS (SELECT id FROM background_jobs WHERE status='QUEUED' AND available_at<=now()
    ORDER BY CASE priority WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,created_at FOR UPDATE SKIP LOCKED LIMIT 1)
    UPDATE background_jobs j SET status='PROCESSING',started_at=COALESCE(started_at,now()),attempts=attempts+1,
    lease_until=now()+($2||' seconds')::interval,worker_id=$1,heartbeat_at=now(),progress=GREATEST(progress,5)
    FROM candidate WHERE j.id=candidate.id RETURNING j.*`,[workerId,String(leaseSeconds)]);
  return camel(result.rows[0]);
}
async function heartbeat(client,id,workerId,leaseSeconds=60){return (await client.query(`UPDATE background_jobs SET heartbeat_at=now(),lease_until=now()+($3||' seconds')::interval WHERE id=$1 AND worker_id=$2 AND status='PROCESSING'`,[id,workerId,String(leaseSeconds)])).rowCount>0;}
async function complete(client,id,workerId,result){const row=(await client.query(`UPDATE background_jobs SET status='COMPLETED',progress=100,finished_at=now(),result=$3,lease_until=NULL,worker_id=NULL WHERE id=$1 AND worker_id=$2 AND status='PROCESSING' RETURNING *`,[id,workerId,result])).rows[0];if(!row)throw new AppError('DOCUMENT_CONFLICT','Job tidak lagi dimiliki worker ini.');return camel(row);}
async function fail(client,id,workerId,error){const row=(await client.query(`UPDATE background_jobs SET status=CASE WHEN attempts<max_attempts THEN 'QUEUED' ELSE 'FAILED' END,error=$3,
    available_at=CASE WHEN attempts<max_attempts THEN now()+(power(2,attempts)*interval '10 seconds') ELSE available_at END,
    finished_at=CASE WHEN attempts>=max_attempts THEN now() ELSE NULL END,lease_until=NULL,worker_id=NULL WHERE id=$1 AND worker_id=$2 RETURNING *`,[id,workerId,String(error).slice(0,2000)])).rows[0];return camel(row);}
async function recoverExpired(client){return (await client.query(`UPDATE background_jobs SET status=CASE WHEN attempts<max_attempts THEN 'QUEUED' ELSE 'FAILED' END,worker_id=NULL,lease_until=NULL,error='Worker lease expired' WHERE status='PROCESSING' AND lease_until<now()`)).rowCount;}
async function listJobs(client,user,{page=1,limit=25}={}){limit=Math.min(Math.max(Number(limit)||25,1),100);page=Math.max(Number(page)||1,1);const owner=['owner','admin'].includes(user.role),params=[];let scope='TRUE';if(!owner){params.push(user.id);scope=`j.requested_by=$${params.length}`;}const total=Number((await client.query(`SELECT count(*) n FROM background_jobs j WHERE ${scope}`,params)).rows[0].n);params.push(limit,(page-1)*limit);const items=(await client.query(`SELECT j.*,j.job_type type,u.display_name requested_by_name FROM background_jobs j JOIN app_users u ON u.id=j.requested_by WHERE ${scope} ORDER BY j.created_at DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params)).rows.map(camel);return{items,page,limit,total,totalPages:Math.max(Math.ceil(total/limit),1)};}

const MASTER={customers:{table:'customers',search:['code','name','city'],sort:new Set(['code','name','city','created_at'])},suppliers:{table:'suppliers',search:['code','name','category'],sort:new Set(['code','name','category','created_at'])},products:{table:'products',search:['code','name','uom'],sort:new Set(['code','name','created_at'])},employees:{table:'employees',search:['nik','name','department','job_title'],sort:new Set(['nik','name','department','join_date'])}};
const MASTER_FIELDS={customers:['code','name','npwp','city','address','payment_term_days','credit_limit','active'],suppliers:['code','name','npwp','category','rating','bank_name','bank_account','bank_holder','active'],products:['code','name','uom','hpp','price','active'],employees:['nik','name','department','job_title','base_salary','branch_id','bpjs','join_date','active']};
const snake=value=>value.replace(/[A-Z]/g,c=>`_${c.toLowerCase()}`);
async function createMaster(client,name,body,user){const fields=MASTER_FIELDS[name];if(!fields)throw new AppError('RESOURCE_NOT_FOUND');const entries=Object.entries(body||{}).map(([k,v])=>[snake(k),v]).filter(([k,v])=>fields.includes(k)&&v!==undefined);if(!entries.length)throw new AppError('VALIDATION_ERROR','Data master kosong.');const columns=['id',...entries.map(x=>x[0])],values=[randomUUID(),...entries.map(x=>x[1])];if(['customers','suppliers'].includes(name)){columns.push('created_by','updated_by');values.push(user.id,user.id);}const params=values.map((_,i)=>`$${i+1}`);return camel((await client.query(`INSERT INTO ${name}(${columns.join(',')}) VALUES(${params.join(',')}) RETURNING *`,values)).rows[0]);}
async function updateMaster(client,name,id,body,user){const fields=MASTER_FIELDS[name];if(!fields)throw new AppError('RESOURCE_NOT_FOUND');const entries=Object.entries(body||{}).map(([k,v])=>[snake(k),v]).filter(([k,v])=>fields.includes(k)&&v!==undefined);if(!entries.length)throw new AppError('VALIDATION_ERROR','Tidak ada perubahan valid.');const values=[id],sets=entries.map(([k,v])=>{values.push(v);return`${k}=$${values.length}`;});sets.push('updated_at=now()');if(['customers','suppliers'].includes(name)){values.push(user.id);sets.push(`updated_by=$${values.length}`);}const row=(await client.query(`UPDATE ${name} SET ${sets.join(',')} WHERE id=$1 RETURNING *`,values)).rows[0];if(!row)throw new AppError('RESOURCE_NOT_FOUND');return camel(row);}
async function listMaster(client,name,query={}){const cfg=MASTER[name];if(!cfg)throw new AppError('RESOURCE_NOT_FOUND');const limit=Math.min(Math.max(Number(query.limit)||25,1),100),page=Math.max(Number(query.page)||1,1),params=[];let where='TRUE';if(query.q){params.push(`%${String(query.q).slice(0,120)}%`);where='('+cfg.search.map(c=>`${c} ILIKE $1`).join(' OR ')+')';}const sort=cfg.sort.has(query.sortKey)?query.sortKey:name==='employees'?'name':'code',dir=query.sortDir==='desc'?'DESC':'ASC';params.push(limit,(page-1)*limit);const li=params.length-1,off=params.length;const from=name==='employees'?'employees m LEFT JOIN branches b ON b.id=m.branch_id':`${cfg.table} m`;const select=name==='employees'?'m.*,b.name branch_name':'m.*';const qualifiedWhere=where.replace(/\b(code|name|city|category|uom|nik|department|job_title)\b/g,'m.$1');const items=(await client.query(`SELECT ${select} FROM ${from} WHERE ${qualifiedWhere} ORDER BY m.${sort} ${dir} LIMIT $${li} OFFSET $${off}`,params)).rows.map(camel);const total=Number((await client.query(`SELECT count(*) n FROM ${from} WHERE ${qualifiedWhere}`,query.q?[params[0]]:[])).rows[0].n);return{items,page,limit,total,totalPages:Math.max(Math.ceil(total/limit),1)};}
async function listInventory(client,user,{page=1,limit=25,q}={}){limit=Math.min(Math.max(Number(limit)||25,1),100);page=Math.max(Number(page)||1,1);const params=[];let where='TRUE';if(!['owner','admin'].includes(user.role)&&user.branchScope!=='*'){params.push(user.branchId);where+=` AND i.warehouse_id=$${params.length}`;}if(q){params.push(`%${String(q).slice(0,120)}%`);where+=` AND (p.code ILIKE $${params.length} OR p.name ILIKE $${params.length})`;}const total=Number((await client.query(`SELECT count(*) n FROM inventory_balances i JOIN products p ON p.id=i.product_id WHERE ${where}`,params)).rows[0].n);params.push(limit,(page-1)*limit);const items=(await client.query(`SELECT i.*,p.code product_code,p.name product_name,p.uom,b.code warehouse_code,b.name warehouse_name FROM inventory_balances i JOIN products p ON p.id=i.product_id JOIN branches b ON b.id=i.warehouse_id WHERE ${where} ORDER BY p.code LIMIT $${params.length-1} OFFSET $${params.length}`,params)).rows.map(camel);return{items,page,limit,total,totalPages:Math.max(Math.ceil(total/limit),1)};}

module.exports={notify,listNotifications,unreadCount,markRead,markAllRead,enqueue,claim,heartbeat,complete,fail,recoverExpired,listJobs,listMaster,createMaster,updateMaster,listInventory,JOBS};
