'use strict';
const {randomUUID}=require('node:crypto');const {AppError}=require('../../../core/errors');

async function syncDocumentLines(client,documentId,lines){
  if(!Array.isArray(lines))return;if(lines.length>500)throw new AppError('VALIDATION_ERROR','Maksimal 500 baris per dokumen.');
  await client.query('DELETE FROM document_lines WHERE document_id=$1',[documentId]);
  for(let i=0;i<lines.length;i++){const line=lines[i],qty=Number(line.qty),price=Number(line.unitPrice??line.price??0),discount=Number(line.discountPct||0),tax=Number(line.taxPct??0);if(!(qty>0)||price<0||discount<0||discount>100||tax<0||tax>100)throw new AppError('VALIDATION_ERROR',`Baris ${i+1} tidak valid.`);const base=qty*price*(1-discount/100),total=Math.round((base+base*tax/100)*100)/100;await client.query(`INSERT INTO document_lines(id,document_id,line_no,product_id,description,qty,uom,unit_price,discount_pct,tax_pct,line_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[randomUUID(),documentId,i+1,line.productId||null,line.description||line.name||`Baris ${i+1}`,qty,line.uom||null,price,discount,tax,total]);}
}

async function claimPosting(client,doc,user,kind){const row=(await client.query(`INSERT INTO document_postings(document_id,posting_kind,posted_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING document_id`,[doc.id,kind,user.id])).rows[0];return!!row;}
async function finishPosting(client,doc,kind,result){await client.query('UPDATE document_postings SET result=$3 WHERE document_id=$1 AND posting_kind=$2',[doc.id,kind,result]);}
async function balance(client,productId,warehouseId,delta,user,doc,movementType){
  if(!productId||!warehouseId)throw new AppError('VALIDATION_ERROR','Produk dan gudang wajib untuk posting stok.');
  await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`stock:${productId}:${warehouseId}`]);
  await client.query(`INSERT INTO inventory_balances(id,product_id,warehouse_id) VALUES($1,$2,$3) ON CONFLICT(product_id,warehouse_id) DO NOTHING`,[randomUUID(),productId,warehouseId]);
  const current=(await client.query(`SELECT i.*,p.hpp FROM inventory_balances i JOIN products p ON p.id=i.product_id WHERE i.product_id=$1 AND i.warehouse_id=$2 FOR UPDATE OF i`,[productId,warehouseId])).rows[0];if(!current)throw new AppError('RESOURCE_NOT_FOUND','Produk stok tidak ditemukan.');const next=Number(current.qty_on_hand)+delta;if(next<0)throw new AppError('VALIDATION_ERROR',`Stok ${productId} tidak mencukupi.`);const cost=Number(current.hpp||0),nextValue=Math.max(0,Number(current.value_idr)+delta*cost);
  await client.query('UPDATE inventory_balances SET qty_on_hand=$3,value_idr=$4,version=version+1,updated_at=now() WHERE product_id=$1 AND warehouse_id=$2',[productId,warehouseId,next,nextValue]);
  await client.query(`INSERT INTO inventory_movements(product_id,warehouse_id,document_id,movement_type,qty,unit_cost,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[productId,warehouseId,doc.id,movementType,Math.abs(delta),cost,user.id]);return{productId,warehouseId,delta,qtyOnHand:next,unitCost:cost};
}
async function postInventory(client,doc,user){const types={GOODS_RECEIPT:'RECEIPT',MATERIAL_ISSUE:'ISSUE',STOCK_ADJUSTMENT:'ADJUSTMENT',STOCK_TRANSFER:'TRANSFER_OUT'};if(!types[doc.documentType]||doc.status!=='COMPLETED')return null;if(!await claimPosting(client,doc,user,'INVENTORY'))return{replay:true};const lines=(await client.query('SELECT * FROM document_lines WHERE document_id=$1 ORDER BY line_no',[doc.id])).rows;if(!lines.length)throw new AppError('VALIDATION_ERROR','Posting stok membutuhkan baris dokumen.');const result=[];
  for(const line of lines){const qty=Number(line.qty);if(doc.documentType==='GOODS_RECEIPT')result.push(await balance(client,line.product_id,doc.payload?.warehouseId||doc.branchId,qty,user,doc,'RECEIPT'));else if(doc.documentType==='MATERIAL_ISSUE')result.push(await balance(client,line.product_id,doc.payload?.warehouseId||doc.branchId,-qty,user,doc,'ISSUE'));else if(doc.documentType==='STOCK_ADJUSTMENT'){const delta=doc.payload?.adjustmentDirection==='OUT'?-qty:qty;result.push(await balance(client,line.product_id,doc.payload?.warehouseId||doc.branchId,delta,user,doc,'ADJUSTMENT'));}else{const to=doc.payload?.toWarehouseId;if(!to)throw new AppError('VALIDATION_ERROR','Gudang tujuan wajib untuk transfer.');result.push(await balance(client,line.product_id,doc.payload?.fromWarehouseId||doc.branchId,-qty,user,doc,'TRANSFER_OUT'));result.push(await balance(client,line.product_id,to,qty,user,doc,'TRANSFER_IN'));}}
  await finishPosting(client,doc,'INVENTORY',{movements:result});return{movements:result};
}
const ACCOUNTING_RULES={INVOICE:{status:'APPROVED',debit:'1200',credit:'4100'},CUSTOMER_PAYMENT:{status:'CLOSED',debit:'1100',credit:'1200'},SUPPLIER_INVOICE:{status:'APPROVED',debit:'6100',credit:'2100'},SUPPLIER_PAYMENT:{status:'CLOSED',debit:'2100',credit:'1100'},EXPENSE:{status:'CLOSED',debit:'6100',credit:'1100'}};
async function ensureOpenPeriod(client,doc){const stamp=doc.documentType==='PAYROLL_RUN'&&doc.payload?.period?`${doc.payload.period}-01`:doc.createdAt instanceof Date?doc.createdAt.toISOString():String(doc.createdAt||new Date().toISOString()),period=stamp.slice(0,7);await client.query(`INSERT INTO accounting_periods(id,period,status) VALUES($1,$2,'OPEN') ON CONFLICT(period) DO NOTHING`,[randomUUID(),period]);const p=(await client.query('SELECT status FROM accounting_periods WHERE period=$1 FOR UPDATE',[period])).rows[0];if(p.status!=='OPEN')throw new AppError('STATUS_INVALID',`Periode ${period} sudah ditutup.`);return period;}
async function accountMap(client,codes){return(await client.query('SELECT id,code FROM chart_of_accounts WHERE code=ANY($1) AND active',[codes])).rows.reduce((o,r)=>(o[r.code]=r.id,o),{});}
async function postAccounting(client,doc,user){if(doc.documentType==='JOURNAL')return postManualJournal(client,doc,user);if(doc.documentType==='PAYROLL_RUN')return postPayroll(client,doc,user);const rule=ACCOUNTING_RULES[doc.documentType];if(!rule||doc.status!==rule.status)return null;if(!await claimPosting(client,doc,user,'ACCOUNTING'))return{replay:true};const amount=Number(doc.amount);if(!(amount>0))throw new AppError('VALIDATION_ERROR','Nilai posting jurnal harus lebih dari nol.');const period=await ensureOpenPeriod(client,doc),accounts=await accountMap(client,[rule.debit,rule.credit]);if(!accounts[rule.debit]||!accounts[rule.credit])throw new AppError('RESOURCE_NOT_FOUND','Akun posting belum dikonfigurasi.');await client.query(`INSERT INTO journal_lines(id,journal_document_id,account_id,debit,credit,memo) VALUES($1,$2,$3,$4,0,$5),($6,$2,$7,0,$4,$5)`,[randomUUID(),doc.id,accounts[rule.debit],amount,`${doc.documentNumber} · auto posting`,randomUUID(),accounts[rule.credit]]);await finishPosting(client,doc,'ACCOUNTING',{period,debit:rule.debit,credit:rule.credit,amount});return{period,debit:rule.debit,credit:rule.credit,amount};}
async function postManualJournal(client,doc,user){if(doc.status!=='APPROVED')return null;if(!await claimPosting(client,doc,user,'ACCOUNTING'))return{replay:true};const lines=doc.payload?.journalLines;if(!Array.isArray(lines)||lines.length<2)throw new AppError('VALIDATION_ERROR','Jurnal manual membutuhkan minimal dua baris.');const debit=lines.reduce((n,x)=>n+Number(x.debit||0),0),credit=lines.reduce((n,x)=>n+Number(x.credit||0),0);if(!(debit>0)||Math.abs(debit-credit)>.01)throw new AppError('VALIDATION_ERROR','Total debit dan kredit jurnal harus seimbang.');const period=await ensureOpenPeriod(client,doc),codes=[...new Set(lines.map(x=>String(x.accountCode||'')))],accounts=await accountMap(client,codes);if(codes.some(code=>!accounts[code]))throw new AppError('RESOURCE_NOT_FOUND','Salah satu akun jurnal tidak ditemukan.');for(const line of lines){const d=Number(line.debit||0),c=Number(line.credit||0);if(d<0||c<0||d&&c||!d&&!c)throw new AppError('VALIDATION_ERROR','Baris jurnal harus memiliki tepat satu sisi debit/kredit.');await client.query(`INSERT INTO journal_lines(id,journal_document_id,account_id,debit,credit,memo) VALUES($1,$2,$3,$4,$5,$6)`,[randomUUID(),doc.id,accounts[line.accountCode],d,c,String(line.memo||doc.title).slice(0,500)]);}await finishPosting(client,doc,'ACCOUNTING',{period,debit,credit,manual:true});return{period,debit,credit,manual:true};}
async function postPayroll(client,doc,user){if(doc.status!=='APPROVED')return null;if(!await claimPosting(client,doc,user,'ACCOUNTING'))return{replay:true};const net=Number(doc.amount),tax=Number(doc.payload?.pph21||0),bpjs=Number(doc.payload?.bpjs||0),period=await ensureOpenPeriod(client,doc),accounts=await accountMap(client,['6200','6210','2200','2300','2400']);if(Object.keys(accounts).length<5)throw new AppError('RESOURCE_NOT_FOUND','Akun payroll belum lengkap.');const rows=[['6200',net+tax,0],['6210',bpjs,0],['2200',0,net],['2300',0,tax],['2400',0,bpjs]];for(const [code,debit,credit] of rows)if(debit||credit)await client.query(`INSERT INTO journal_lines(id,journal_document_id,account_id,debit,credit,memo) VALUES($1,$2,$3,$4,$5,$6)`,[randomUUID(),doc.id,accounts[code],debit,credit,`${doc.documentNumber} · payroll`]);await finishPosting(client,doc,'ACCOUNTING',{period,net,tax,bpjs});return{period,net,tax,bpjs};}
async function postDocument(client,doc,user){return{inventory:await postInventory(client,doc,user),accounting:await postAccounting(client,doc,user)};}
module.exports={syncDocumentLines,postInventory,postAccounting,postManualJournal,postPayroll,postDocument};
