'use strict';
const businessDate = require('../../core/business-date');
const fs=require('node:fs/promises');
const path=require('node:path');
const {randomUUID,createHash}=require('node:crypto');
const {AppError}=require('../../core/errors');
const {camel}=require('../database/repositories/runtime');
const {zipSync,strToU8}=require('fflate');
const ROOT=path.resolve(__dirname,'../../../storage/artifacts');
const xml=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const pdf=value=>String(value??'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7e]/g,'?');
function absolute(relative){const target=path.resolve(ROOT,relative);if(target!==ROOT&&!target.startsWith(ROOT+path.sep))throw new AppError('RESOURCE_NOT_FOUND');return target;}
function pdfBuffer(title,rows=[]){
  const normalized=Array.isArray(rows)?rows:[],perPage=42,pageCount=Math.max(1,Math.ceil(normalized.length/perPage)),objects=['<< /Type /Catalog /Pages 2 0 R >>','',`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`],pageRefs=[];
  const generated=new Date().toISOString(),headers=normalized[0]&&typeof normalized[0]==='object'?Object.keys(normalized[0]):[];
  for(let page=0;page<pageCount;page++){
    const pageRows=normalized.slice(page*perPage,(page+1)*perPage),pageObject=objects.length+1,streamObject=pageObject+1;pageRefs.push(`${pageObject} 0 R`);
    let y=798;const stream=['BT','/F1 14 Tf',`1 0 0 1 48 ${y} Tm`,`(${pdf(title||'MAT ERP V2 Report').slice(0,90)}) Tj`];y-=22;
    stream.push('/F1 8 Tf',`1 0 0 1 48 ${y} Tm`,`(Generated ${pdf(generated)} | Page ${page+1} of ${pageCount}) Tj`);y-=22;
    if(headers.length){stream.push('/F1 8 Tf',`1 0 0 1 48 ${y} Tm`,`(${pdf(headers.join(' | ')).slice(0,125)}) Tj`);y-=16;}
    for(const row of pageRows){const line=typeof row==='object'?headers.map(key=>row[key]??'').join(' | '):String(row);stream.push('/F1 8 Tf',`1 0 0 1 48 ${y} Tm`,`(${pdf(line).slice(0,125)}) Tj`);y-=16;}
    stream.push('/F1 8 Tf','1 0 0 1 48 28 Tm',`(MAT ERP V2 | ${page+1}/${pageCount}) Tj`,'ET');const content=stream.join('\n');
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${streamObject} 0 R >>`,`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`);
  }
  objects[1]=`<< /Type /Pages /Kids [${pageRefs.join(' ')}] /Count ${pageCount} >>`;
  let output='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(output));output+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=Buffer.byteLength(output);output+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(output);
}
function excelBuffer(title,rows=[]){
  const normalized=rows.slice(0,50000),headers=[...new Set(normalized.flatMap(row=>row&&typeof row==='object'?Object.keys(row):['value']))];
  const col=n=>{let s='';for(n++;n>0;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
  const cell=(ref,value,style=0)=>{if(value===null||value===undefined)return`<c r="${ref}" s="${style}"/>`;if(typeof value==='number'&&Number.isFinite(value))return`<c r="${ref}" s="${style}"><v>${value}</v></c>`;if(typeof value==='boolean')return`<c r="${ref}" t="b" s="${style}"><v>${value?1:0}</v></c>`;return`<c r="${ref}" t="inlineStr" s="${style}"><is><t xml:space="preserve">${xml(value)}</t></is></c>`;};
  const last=col(Math.max(headers.length-1,0)),widths=headers.map((h,i)=>Math.min(45,Math.max(12,String(h).length+2,...normalized.slice(0,200).map(r=>String(r&&typeof r==='object'?r[h]??'':r??'').length+2))));
  const dataRows=normalized.map((row,index)=>`<row r="${index+4}">${headers.map((h,i)=>cell(`${col(i)}${index+4}`,row&&typeof row==='object'?row[h]:row)).join('')}</row>`).join('');
  const sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="3" topLeftCell="A4" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData><row r="1" ht="24" customHeight="1">${cell('A1',title||'MAT ERP V2 Report',2)}</row><row r="2">${cell('A2',`Generated ${new Date().toISOString()}`,3)}</row><row r="3">${headers.map((h,i)=>cell(`${col(i)}3`,h,1)).join('')}</row>${dataRows}</sheetData><mergeCells count="2"><mergeCell ref="A1:${last}1"/><mergeCell ref="A2:${last}2"/></mergeCells><autoFilter ref="A3:${last}${Math.max(normalized.length+3,3)}"/></worksheet>`;
  const files={
    '[Content_Types].xml':strToU8(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`),
    '_rels/.rels':strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`),
    'xl/workbook.xml':strToU8(`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Data" sheetId="1" r:id="rId1"/></sheets></workbook>`),
    'xl/_rels/workbook.xml.rels':strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`),
    'xl/styles.xml':strToU8(`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="3"><font><sz val="10"/><name val="Aptos"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Aptos"/></font><font><b/><color rgb="FF162033"/><sz val="16"/><name val="Aptos Display"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF162033"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs></styleSheet>`),
    'xl/worksheets/sheet1.xml':strToU8(sheet)
  };
  return Buffer.from(zipSync(files,{level:6}));
}
async function create(client,{job,kind,title,rows}){const isPdf=kind==='pdf',buffer=isPdf?pdfBuffer(title,rows):excelBuffer(title,rows),extension=isPdf?'.pdf':'.xlsx',mimeType=isPdf?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',fileName=`${String(title||'artifact').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,80)}-${businessDate.today()}${extension}`,relative=path.join(String(new Date().getUTCFullYear()),`${randomUUID()}${extension}`),target=absolute(relative),retention=Math.min(Math.max(Number(job.artifactRetentionDays)||30,1),3650);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,buffer,{flag:'wx',mode:0o600});const checksum=createHash('sha256').update(buffer).digest('hex');try{return camel((await client.query(`INSERT INTO generated_artifacts(job_id,requested_by,file_name,mime_type,storage_path,size_bytes,checksum_sha256,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()+($8||' days')::interval) RETURNING *`,[job.id,job.requestedBy,fileName,mimeType,relative,buffer.length,checksum,String(retention)])).rows[0]);}catch(error){await fs.unlink(target).catch(()=>{});throw error;}}
async function list(client,user){const elevated=['owner','system_admin','auditor'].includes(user.role),rows=(await client.query(`SELECT * FROM generated_artifacts WHERE expires_at>now() AND ($1::boolean OR requested_by=$2) ORDER BY created_at DESC LIMIT 100`,[elevated,user.id])).rows;return rows.map(camel);}
async function download(client,id,user){const elevated=['owner','system_admin','auditor'].includes(user.role),row=(await client.query(`SELECT * FROM generated_artifacts WHERE id=$1 AND expires_at>now() AND ($2::boolean OR requested_by=$3)`,[id,elevated,user.id])).rows[0];if(!row)throw new AppError('RESOURCE_NOT_FOUND');const item=camel(row),buffer=await fs.readFile(absolute(item.storagePath));if(createHash('sha256').update(buffer).digest('hex')!==item.checksumSha256)throw new AppError('INTERNAL','Integritas artifact gagal diverifikasi.');return{item,buffer};}
module.exports={ROOT,pdfBuffer,excelBuffer,create,list,download};
