'use strict';
const fs=require('node:fs/promises');
const path=require('node:path');
const {randomUUID,createHash}=require('node:crypto');
const {AppError}=require('../../core/errors');
const {camel}=require('../database/repositories/runtime');
const ROOT=path.resolve(__dirname,'../../../storage/artifacts');
const xml=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const pdf=value=>String(value??'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7e]/g,'?');
function absolute(relative){const target=path.resolve(ROOT,relative);if(target!==ROOT&&!target.startsWith(ROOT+path.sep))throw new AppError('RESOURCE_NOT_FOUND');return target;}
function pdfBuffer(title,rows=[]){
  const lines=[title,...rows.slice(0,45).map(row=>typeof row==='object'?Object.values(row).join(' | '):String(row))];let y=800;
  const stream=['BT','/F1 11 Tf',...lines.flatMap((line,index)=>{const item=[`1 0 0 1 48 ${y} Tm`,`${index===0?'14':'10'} TL`, `(${pdf(line).slice(0,110)}) Tj`];y-=index===0?28:16;return item;}),'ET'].join('\n');
  const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
  let output='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(Buffer.byteLength(output));output+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=Buffer.byteLength(output);output+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(output);
}
function excelBuffer(title,rows=[]){const normalized=rows.slice(0,5000),headers=[...new Set(normalized.flatMap(row=>row&&typeof row==='object'?Object.keys(row):['value']))];const cells=values=>values.map(v=>`<Cell><Data ss:Type="${typeof v==='number'?'Number':'String'}">${xml(v)}</Data></Cell>`).join('');return Buffer.from(`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Data"><Table><Row>${cells(headers)}</Row>${normalized.map(row=>`<Row>${cells(headers.map(h=>row&&typeof row==='object'?row[h]:row))}</Row>`).join('')}</Table></Worksheet></Workbook>`);}
async function create(client,{job,kind,title,rows}){const isPdf=kind==='pdf',buffer=isPdf?pdfBuffer(title,rows):excelBuffer(title,rows),extension=isPdf?'.pdf':'.xls',mimeType=isPdf?'application/pdf':'application/vnd.ms-excel',fileName=`${String(title||'artifact').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,80)}-${new Date().toISOString().slice(0,10)}${extension}`,relative=path.join(String(new Date().getUTCFullYear()),`${randomUUID()}${extension}`),target=absolute(relative);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,buffer,{flag:'wx',mode:0o600});const checksum=createHash('sha256').update(buffer).digest('hex');try{return camel((await client.query(`INSERT INTO generated_artifacts(job_id,requested_by,file_name,mime_type,storage_path,size_bytes,checksum_sha256,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()+interval '30 days') RETURNING *`,[job.id,job.requestedBy,fileName,mimeType,relative,buffer.length,checksum])).rows[0]);}catch(error){await fs.unlink(target).catch(()=>{});throw error;}}
async function list(client,user){const elevated=['owner','admin'].includes(user.role),rows=(await client.query(`SELECT * FROM generated_artifacts WHERE expires_at>now() AND ($1::boolean OR requested_by=$2) ORDER BY created_at DESC LIMIT 100`,[elevated,user.id])).rows;return rows.map(camel);}
async function download(client,id,user){const elevated=['owner','admin'].includes(user.role),row=(await client.query(`SELECT * FROM generated_artifacts WHERE id=$1 AND expires_at>now() AND ($2::boolean OR requested_by=$3)`,[id,elevated,user.id])).rows[0];if(!row)throw new AppError('RESOURCE_NOT_FOUND');const item=camel(row),buffer=await fs.readFile(absolute(item.storagePath));if(createHash('sha256').update(buffer).digest('hex')!==item.checksumSha256)throw new AppError('INTERNAL','Integritas artifact gagal diverifikasi.');return{item,buffer};}
module.exports={ROOT,pdfBuffer,excelBuffer,create,list,download};
