'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {scan}=require('./secret-scan');const {fingerprintRelease}=require('./build-assets');
const ROOT=path.resolve(__dirname,'..'),RELEASE_ROOT=path.resolve(ROOT,'release'),TARGET=path.resolve(RELEASE_ROOT,'MAT-ERP-V2-RELEASE');
if(!TARGET.startsWith(RELEASE_ROOT+path.sep))throw new Error('Target release keluar dari direktori release.');
const allow=['backend','data/migrations','deploy','docs','scripts','src','assets','index.html','favicon.svg','server.js','package.json','package-lock.json','README.md','CHANGELOG.md','.env.example','.gitignore'];
const denyNames=new Set(['.env','.git','node_modules','storage','release','.agents','.claude','.vscode']);
const productionExcluded=new Set(['backend/api.js','backend/selftest.js','backend/modules','backend/workers/queue.js','backend/core/auth.js','backend/core/audit.js','backend/core/documents.js','backend/core/idempotency.js','backend/core/notifications.js','backend/core/numbering.js','backend/infrastructure/database/store.js','backend/infrastructure/database/persistence.js','scripts/accessibility-audit.js','scripts/build-assets.js','scripts/build-release.js','scripts/install-postgres-local.ps1','scripts/load-smoke.js','scripts/load-lan.js','scripts/predeploy-gate.js','scripts/seed-postgres-dev.js','scripts/seed-postgres-uat.js','scripts/seed-postgres-uat-sprint4.js','scripts/smoke-sprint7.js','scripts/ui-smoke-cdp.js','scripts/verify-release-assets.js']);
function copy(relative){if(relative.split(/[\\/]/).some(x=>denyNames.has(x)))throw new Error(`Path terlarang: ${relative}`);const source=path.resolve(ROOT,relative),target=path.resolve(TARGET,relative);if(!source.startsWith(ROOT+path.sep)||!target.startsWith(TARGET+path.sep))throw new Error(`Path release tidak aman: ${relative}`);if(!fs.existsSync(source))return;fs.cpSync(source,target,{recursive:true,filter:src=>{const rel=path.relative(ROOT,src).replace(/\\/g,'/');return!denyNames.has(path.basename(src))&&!productionExcluded.has(rel)&&!/\.(?:log|err|tmp|bak|dump|enc)$/i.test(src);}});}
function allFiles(dir,out=[]){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())allFiles(full,out);else out.push(full);}return out;}
function hash(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function build(){const findings=scan();if(findings.length)throw new Error(`Secret scan gagal: ${findings.map(x=>`${x.file}:${x.kind}`).join(', ')}`);if(fs.existsSync(TARGET)){const resolved=path.resolve(TARGET);if(!resolved.startsWith(RELEASE_ROOT+path.sep))throw new Error('Refuse remove target tidak aman.');fs.rmSync(resolved,{recursive:true,force:true});}fs.mkdirSync(TARGET,{recursive:true});allow.forEach(copy);const packageFile=path.join(TARGET,'package.json'),pkg=JSON.parse(fs.readFileSync(packageFile,'utf8'));pkg.scripts={start:'node server.js','db:health':'node scripts/db.js health','db:status':'node scripts/db.js status','db:migrate':'node scripts/db.js migrate','db:validate':'node scripts/db.js validate','db:grant-runtime':'node scripts/grant-runtime.js','backup:run':'node scripts/backup-postgres.js run','backup:restore-test':'node scripts/backup-postgres.js restore-test','security:rotate-owner':'node scripts/rotate-owner-password.js','security:rotate-runtime':'node scripts/rotate-runtime-secrets.js','security:rotate-fields':'node scripts/rotate-field-encryption.js --apply','security:fields-status':'node scripts/rotate-field-encryption.js','security:data-audit':'node scripts/audit-data-protection.js'};fs.writeFileSync(packageFile,JSON.stringify(pkg,null,2)+'\n');const assetManifest=fingerprintRelease(TARGET);for(const required of ['assets/fonts/manrope-latin-variable.woff2','assets/fonts/plus-jakarta-sans-latin-variable.woff2','assets/icons/navigation/dashboard.png','backend/api-postgres.js'])if(!fs.existsSync(path.join(TARGET,required)))throw new Error(`Berkas release wajib hilang: ${required}`);const navigationIcons=fs.readdirSync(path.join(TARGET,'assets','icons','navigation')).filter(name=>name.endsWith('.png'));if(navigationIcons.length!==21)throw new Error(`Ikon navigasi release tidak lengkap: ${navigationIcons.length}/21`);for(const forbidden of ['.env','test','backend/api.js','backend/selftest.js','backend/modules','backend/workers/queue.js'])if(fs.existsSync(path.join(TARGET,forbidden)))throw new Error(`Berkas development terlarang masuk release: ${forbidden}`);require('./generate-sbom').generate(TARGET);const files=allFiles(TARGET).filter(x=>path.basename(x)!=='release-manifest.json'),manifest={name:'MAT ERP V2',version:require('../package.json').version,environment:'PRODUCTION',createdAt:new Date().toISOString(),migrationLatest:fs.readdirSync(path.join(ROOT,'data','migrations')).filter(x=>/^\d+_.+\.sql$/.test(x)&&!x.endsWith('.down.sql')).sort().at(-1),assetCount:Object.keys(assetManifest.assets).length,files:files.map(file=>({path:path.relative(TARGET,file).replace(/\\/g,'/'),bytes:fs.statSync(file).size,sha256:hash(file)}))};manifest.releaseSha256=crypto.createHash('sha256').update(JSON.stringify(manifest.files)).digest('hex');fs.writeFileSync(path.join(TARGET,'release-manifest.json'),JSON.stringify(manifest,null,2));return manifest;}
if(require.main===module){try{const manifest=build();console.log(JSON.stringify({ok:true,target:TARGET,files:manifest.files.length,releaseSha256:manifest.releaseSha256,migrationLatest:manifest.migrationLatest},null,2));}catch(error){console.error(error.message);process.exit(1);}}
module.exports={build,ROOT,RELEASE_ROOT,TARGET,allow};
