'use strict';
// Stage-aware release gate. LOCAL green never implies production-ready.
require('../backend/core/env').loadEnv();
const {spawnSync,spawn}=require('node:child_process');const path=require('node:path');const fs=require('node:fs');
const ROOT=path.join(__dirname,'..'),STAGE=String(process.env.MAT_DEPLOY_STAGE||'LOCAL').toUpperCase(),results=[];
const step=(name,ok,detail='')=>{results.push({name,ok,detail});console.log(`${ok?'✔':'✖'} ${name}${detail?` — ${detail}`:''}`);return ok;};
function runSync(name,commandLine){const res=spawnSync(commandLine,{cwd:ROOT,shell:true,encoding:'utf8',timeout:300000}),output=`${res.stdout||''}${res.stderr||''}`;return step(name,res.status===0,res.status===0?'':output.split('\n').filter(Boolean).slice(-3).join(' | '));}
function verifyStage(){runSync('Audit aksesibilitas UI','npm run test:a11y');runSync('Visual regression desktop + mobile','npm run test:visual');const env=require('../backend/core/env').validateEnvironment(process.env,{forBoot:STAGE==='PRODUCTION'});let ok=env.valid,detail=`stage=${STAGE}, environment=${env.name}`;if(!['LOCAL','LAN-UAT','PRODUCTION'].includes(STAGE)){ok=false;detail+='; stage tidak dikenal';}if(STAGE==='LAN-UAT'&&env.name!=='LAN-UAT'){ok=false;detail+='; MAT_ENVIRONMENT harus LAN-UAT';}if(STAGE==='PRODUCTION'){const file=path.join(ROOT,'docs','uat','FINAL_SIGNOFF.json');let signoff=null;try{signoff=JSON.parse(fs.readFileSync(file,'utf8'));}catch{}if(!signoff?.approved||!signoff?.owner||!signoff?.approvedAt){ok=false;detail+='; Owner UAT sign-off belum valid';}}if(env.errors.length)detail+=`; ${env.errors.join(' ')}`;return step('Environment & activation stage',ok,detail);}
async function probeHealth(){const port=40000+Math.floor(Math.random()*10000),child=spawn(process.execPath,['server.js'],{cwd:ROOT,env:{...process.env,PORT:String(port),MAT_BACKUP_SCHEDULE_ENABLED:'0'},stdio:['ignore','pipe','pipe']});let bootLog='';child.stdout.on('data',d=>{bootLog+=d});child.stderr.on('data',d=>{bootLog+=d});try{let healthy=false,detail='';for(let attempt=0;attempt<20&&!healthy;attempt++){await new Promise(r=>setTimeout(r,500));try{const res=await fetch(`http://127.0.0.1:${port}/api/health`),body=await res.json();healthy=res.status===200&&body.ok===true&&body.db==='up';detail=`HTTP ${res.status}, db=${body.db}`;}catch(error){detail=error.message;}}if(!healthy&&bootLog)detail+=` | boot: ${bootLog.split('\n').filter(Boolean).slice(-2).join(' ')}`;return step('Boot runtime PostgreSQL + /api/health',healthy,detail);}finally{child.stdout.destroy();child.stderr.destroy();child.kill('SIGTERM');await new Promise(r=>setTimeout(r,400));if(child.exitCode===null)child.kill('SIGKILL');}}
async function verifyBackupFreshness(){const {getPool,close}=require('../backend/infrastructure/database/pool');try{const row=(await getPool().query(`SELECT started_at,restore_tested FROM backup_runs WHERE status='COMPLETED' ORDER BY finished_at DESC LIMIT 1`)).rows[0];if(!row)return step('Backup terakhir + restore drill',false,'Belum ada backup COMPLETED.');const ageHours=(Date.now()-new Date(row.started_at).getTime())/3600000,drill=(await getPool().query(`SELECT count(*)::int n FROM backup_runs WHERE restore_tested=true`)).rows[0],ok=ageHours<=48&&drill.n>0;return step('Backup terakhir + restore drill',ok,`umur ${ageHours.toFixed(1)} jam, drill sukses ${drill.n}`);}finally{await close();}}
async function verifyRuntimeControls(){const {getPool,close}=require('../backend/infrastructure/database/pool');try{const r=(await getPool().query(`SELECT
  EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='background_jobs' AND column_name='execution_key') jobs,
  EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='file_metadata' AND column_name='scan_engine') files,
  EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='user_sessions' AND column_name='previous_csrf_token_hash') sessions,
  to_regclass('public.user_role_assignments') IS NOT NULL iam,
  to_regclass('public.sod_rules') IS NOT NULL sod,
  to_regclass('public.access_reviews') IS NOT NULL reviews,
  EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='business_documents' AND column_name='approval_policy_snapshot') policy_snapshot,
  (SELECT count(*)::int FROM approval_policy_versions WHERE status='ACTIVE' AND effective_from<=now() AND (effective_until IS NULL OR effective_until>now())) active_policies,
  (SELECT count(*)::int FROM background_jobs WHERE status IN('CLAIMED','RUNNING') AND lease_until<now()) expired_jobs,
  (SELECT count(*)::int FROM user_role_assignments WHERE status='ACTIVE' AND effective_until<=now()) expired_assignments,
  (SELECT count(*)::int FROM file_metadata WHERE scan_status='CLEAN' AND scanned_at IS NULL AND uploaded_at>(SELECT applied_at FROM schema_migrations WHERE filename='015_r012_runtime_hardening.sql')) unscanned_clean`)).rows[0],ok=r.jobs&&r.files&&r.sessions&&r.iam&&r.sod&&r.reviews&&r.policy_snapshot&&r.active_policies>0&&r.expired_jobs===0&&r.expired_assignments===0&&r.unscanned_clean===0;return step('R012 + R013 runtime controls',ok,`job=${r.jobs}, file=${r.files}, session=${r.sessions}, iam=${r.iam}, sod=${r.sod}, reviews=${r.reviews}, policy=${r.active_policies}, expired-job=${r.expired_jobs}, expired-access=${r.expired_assignments}, unscanned-clean=${r.unscanned_clean}`);}finally{await close();}}
(async()=>{console.log(`=== MAT ERP V2 — Gerbang ${STAGE} ===`);verifyStage();runSync('Secret scan repository','npm run security:scan');runSync('Dependency vulnerability audit','npm audit --omit=dev --audit-level=high');runSync('Validasi migrasi + checksum','npm run db:validate');runSync('Suite tes otomatis','npm test');runSync('Load smoke read/API','npm run load:smoke');await probeHealth();await verifyRuntimeControls();await verifyBackupFreshness();const failed=results.filter(r=>!r.ok),ready=STAGE==='PRODUCTION'?'PRODUCTION READY':STAGE==='LAN-UAT'?'LAN-UAT READY':'LOCAL BUILD READY';console.log(`\n${failed.length?`❌ ${STAGE} DIBLOKIR — ${failed.length} pemeriksaan gagal.`:`✅ ${ready} — bukan pengganti gate tahap berikutnya.`}`);process.exit(failed.length?1:0);})().catch(error=>{console.error('Gerbang pre-deploy error:',error.message);process.exit(1);});
